"""
make_bindings.py — generate a pack's opcode->handler bindings skeleton.

    python3 tools/extract/make_bindings.py <var-dir> <pack-id> > packs/<id>/bindings.json

WHY JSON AND NOT TOML. docs/LAYOUT.md said `bindings.toml`. Godot has no TOML
parser, so TOML would mean shipping one, and the oracle would need to agree with
it byte for byte — a parser both languages must match is exactly the kind of
thing that silently diverges. Godot's own ConfigFile is native but its values are
Variant-encoded, which Python's configparser does not reproduce. JSON is parsed
natively by both with zero code. The file is generated and then hand-edited, so
readability matters more than terseness; it is emitted one entry per line.

WHAT IS PRE-FILLED. Handlers are derived only where the ability_num name maps
unambiguously onto a known primitive — flat stat deltas, spell grants,
categorical immunities. Everything else is emitted with an empty handler, which
is what makes the unbound count an honest progress meter rather than a
flattering one. Guessing here would defeat the purpose.

WHY BINDINGS ARE PER PACK. Opcode 30 is magic immunity in Genesis and
armour-piercing strike in New Horizons. The opcode->behaviour mapping is content,
so each pack carries its own file.
"""

from __future__ import annotations

import json
import re
import sys

sys.path.insert(0, "tools/var")

import eador_var as E
import hooks as H


# Stat names as they appear in ability_num, mapped onto the parameter a single
# `stat_delta` primitive takes. This is the largest unambiguous family.
STATS = {
    "Жизнь": "life",
    "Здоровье": "life",
    "Атака": "attack",
    "Контратака": "counter_attack",
    "Защита": "defence",
    "Защита от выстрела": "ranged_defence",
    # Vanilla spelling — the vanilla->NH rename reaches even the core stats.
    "Защита от стрел": "ranged_defence",
    "Дальность": "shooting_range",
    "Восстановление": "stamina_recovery",
    "Восстановление сил": "stamina_recovery",
    "Сопротивление": "resist",
    "Скорость": "speed",
    "Дистанционная атака": "ranged_attack",
    "Дальность выстрела": "shooting_range",
    "Запас снарядов": "ammo",
    "Выносливость": "stamina",
    "Боевой дух": "morale",
    "Инициатива": "initiative",
}


def derive(name: str, hook: str, conf: str):
    """Return (handler, params) or (None, {}) when nothing is safely derivable."""
    base = re.sub(r"\s*[+-]\d+$", "", (name or "").strip())

    if base in STATS:
        return "stat_delta", {"stat": STATS[base]}

    m = re.match(r'^Заклятье\s*[«"](.+)[»"]\s*$', name or "")
    if m:
        # 276 of 598 NH opcodes are this. One primitive, spell named as a param.
        return "grant_spell", {"spell": m.group(1)}

    m = re.match(r"^Иммунитет к (.+)$", name or "")
    if m:
        return "immunity", {"against": m.group(1)}

    m = re.match(r"^Устойчивость к (.+)$", name or "")
    if m:
        return "resistance", {"against": m.group(1)}

    return None, {}


def build(var_dir: str, pack_id: str) -> dict:
    ab = E.parse(f"{var_dir}/ability_num.var")
    rows = {r["opcode"]: r for r in H.build(var_dir)}

    entries = {}
    for r in ab.records:
        n = r.get("Number")
        name = r.get("Name")
        if not isinstance(n, int) or not name or name == "Пусто":
            continue
        row = rows.get(n, {})
        hook = row.get("hook", "UNCLASSIFIED")
        conf = row.get("conf", "low")
        handler, params = derive(name, hook, conf)
        entry = {
            "name": name,
            "hook": hook,
            "handler": handler or "",
            "uses": row.get("uses", 0),
        }
        if params:
            entry["params"] = params
        if not handler:
            entry["hook_confidence"] = conf
        entries[str(n)] = entry

    bound = sum(1 for e in entries.values() if e["handler"])
    return {
        "pack": pack_id,
        "note": "generated by tools/extract/make_bindings.py — hand-edit the empty handlers",
        "summary": {
            "opcodes": len(entries),
            "bound": bound,
            "unbound": len(entries) - bound,
        },
        "abilities": entries,
    }


def dumps(payload: dict) -> str:
    """One entry per line: readable diffs when a handler gets filled in."""
    head = json.dumps(
        {k: v for k, v in payload.items() if k != "abilities"},
        ensure_ascii=False, indent=1,
    )
    lines = [head[:-2] + ",", ' "abilities": {']
    items = sorted(payload["abilities"].items(), key=lambda kv: int(kv[0]))
    for i, (k, v) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lines.append('  "%s": %s%s' % (k, json.dumps(v, ensure_ascii=False), comma))
    lines.append(" }")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(2)
    payload = build(sys.argv[1], sys.argv[2])
    s = payload["summary"]
    print(
        "%s: %d opcodes, %d bound, %d unbound"
        % (payload["pack"], s["opcodes"], s["bound"], s["unbound"]),
        file=sys.stderr,
    )
    sys.stdout.write(dumps(payload))
