"""Generate the cross-language fixtures the GDScript tests consume.

    python3 oracle/make_fixtures.py tests/fixtures/

Writes rng_fixture.json and pipeline_fixture.json.

COMMIT THE OUTPUT. Do not wire this into the test run. A fixture regenerated at
test time records whatever the code currently does, so the test can never fail
and reviews show no diff — the same class of defect as the RNG bug, where every
check passed while the property under test was broken. Regeneration must be a
deliberate act whose diff is reviewable: if a formula changes, the changed
expected values are exactly what a reviewer needs to see.

The RNG-free pipeline cases carry exact expected values and are meaningful
before the RNG port is confirmed. The RNG-dependent cases assume test_rng.gd
passes, so run that first.
"""
import json
import os
import sys

import combat
import actions
import turn
import content as content_mod
import battlefield as bfmod
from combat import AttackKind, Combatant, Rng

KIND = {"melee": AttackKind.MELEE, "counter": AttackKind.COUNTER, "ranged": AttackKind.RANGED}
KIND_ORD = {"melee": 0, "counter": 1, "ranged": 2}


def make(**kw):
    c = Combatant()
    for k, v in kw.items():
        if k == "flags":
            c.flags = set(v)
        else:
            setattr(c, k, v)
    return c


CASES = [
    ("healthy melee",            dict(name="a", attack=8, life_base=17, life=17), "melee"),
    ("additive bonus only",      dict(name="a", attack=8, attack_bonus=3, life_base=17, life=17), "melee"),
    ("wounded",                  dict(name="a", attack=8, life_base=17, life=5), "melee"),
    ("wounded + painless",       dict(name="a", attack=8, life_base=17, life=5,
                                      flags=["Не чувствует боли"]), "melee"),
    ("low stamina",              dict(name="a", attack=10, stamina=3, life_base=20, life=20), "melee"),
    ("zero stamina",             dict(name="a", attack=10, stamina=0, life_base=20, life=20), "melee"),
    ("zero stamina + tireless",  dict(name="a", attack=10, stamina=0, life_base=20, life=20,
                                      flags=["Неутомимый"]), "melee"),
    ("all three multipliers",    dict(name="a", attack=12, attack_bonus=2, stamina=2,
                                      life_base=30, life=6, morale=10, morale_base=10), "melee"),
    ("rage suppresses wound",    dict(name="a", attack=12, life_base=30, life=6,
                                      flags=["Боевое безумие"]), "melee"),
    ("counter attack stat",      dict(name="a", counter_attack=6, life_base=17, life=17), "counter"),
    ("ranged attack stat",       dict(name="a", ranged_attack=7, life_base=17, life=17), "ranged"),
]

DEF_CASES = [
    ("plain defence",        dict(name="d", defence=5, ranged_defence=7), "melee"),
    ("plain ranged defence", dict(name="d", defence=5, ranged_defence=7), "ranged"),
    ("defence bonus",        dict(name="d", defence=5, defence_bonus=3), "melee"),
    ("exhausted halving",    dict(name="d", defence=7, ranged_defence=9, stamina=0), "melee"),
    ("exhausted ranged",     dict(name="d", defence=7, ranged_defence=9, stamina=0), "ranged"),
    ("exhausted odd floor",  dict(name="d", defence=1, stamina=0), "melee"),
    ("exhausted tireless",   dict(name="d", defence=7, stamina=0, flags=["Неутомимый"]), "melee"),
]

out = {
    "note": "generated by oracle/make_fixtures.py — do not hand-edit",
    "attack_value": [],
    "defence_value": [],
    "multipliers": {"wound": [], "stamina": []},
    "roll_attack": [],
    "resolve": [],
}

for label, kw, kind in CASES:
    c = make(**kw)
    v, _ = combat.current_attack(c, KIND[kind])
    out["attack_value"].append({
        "label": label, "kind": KIND_ORD[kind], "unit": kw, "expected": round(v, 6),
    })

for label, kw, kind in DEF_CASES:
    c = make(**kw)
    v, _ = combat.current_defence(c, KIND[kind])
    out["defence_value"].append({
        "label": label, "kind": KIND_ORD[kind], "unit": kw, "expected": v,
    })

for pct in (100, 60, 50, 49, 40, 30, 20, 10, 1):
    c = make(life_base=100, life=pct)
    out["multipliers"]["wound"].append({"life": pct, "life_base": 100,
                                        "expected": round(combat.wound_mod(c)[0], 6)})
for st in (10, 6, 5, 4, 3, 2, 1, 0):
    c = make(stamina=st)
    out["multipliers"]["stamina"].append({"stamina": st,
                                          "expected": round(combat.stamina_mod(c)[0], 6)})

# RNG-dependent: exact sequences given a fixed seed
for attack in (1, 3, 5, 8, 13, 37):
    r = Rng(1234)
    out["roll_attack"].append({
        "attack": attack, "seed": 1234,
        "expected": [combat.roll_attack(attack, r)[0] for _ in range(12)],
    })

r = Rng(99)
seq = []
atk = make(name="Мечник", attack=8, attack_bonus=2, life_base=17, life=5, stamina=3)
dfn = make(name="Ополченец", defence=3, life_base=12, life=12)
for _ in range(10):
    d, _tr = combat.resolve_attack(atk, dfn, AttackKind.MELEE, r)
    seq.append(d)
out["resolve"].append({
    "label": "wounded exhausted swordsman vs militia", "seed": 99,
    "attacker": dict(name="Мечник", attack=8, attack_bonus=2, life_base=17, life=5, stamina=3),
    "defender": dict(name="Ополченец", defence=3, life_base=12, life=12),
    "kind": 0, "expected": seq,
})

def action_fixture() -> dict:
    """The catalogue plus decidable legality/cost cases.

    The catalogue is exported so the GDScript side builds Actions from data
    rather than duplicating a hardcoded list — which exists are content and
    differ per pack.
    """
    fx = {
        "note": "generated by oracle/make_fixtures.py — do not hand-edit",
        "catalogue": [],
        "cases": [],
    }
    for a in actions.CATALOGUE.values():
        fx["catalogue"].append({
            "id": a.id, "name": a.name, "target": list(actions.Target).index(a.target),
            "cost_stamina": a.cost.stamina, "cost_ammo": a.cost.ammo,
            "consumes_action": a.cost.consumes_action,
            "attack_surcharge": a.cost.attack_surcharge,
            "free_action_for": list(a.cost.free_action_for),
            "magnitude": a.magnitude, "is_attack": a.is_attack,
            "damage_scale": a.damage_scale,
            "suppresses": list(a.suppresses),
            "scales": [list(p) for p in a.scales],
            "excluded_targets": list(a.excluded_targets),
            "suppresses_counterattack": a.suppresses_counterattack,
            "notes": a.notes,
        })

    def case(label, action_id, **actor_kw):
        u = Combatant()
        u.stamina, u.stamina_base, u.ammo = 10, 10, 4
        for k, v in actor_kw.items():
            if k in ("flags", "subtypes"):
                setattr(u, k, set(v))
            else:
                setattr(u, k, v)
        a = actions.CATALOGUE[action_id]
        before = (u.stamina, u.ammo, u.action_spent)
        avail = a.availability(u)
        if avail is actions.Refusal.OK:
            a.pay(u)
        fx["cases"].append({
            "label": label, "action": action_id,
            "actor": {k: (sorted(v) if isinstance(v, set) else v)
                      for k, v in actor_kw.items()},
            "availability": list(actions.Refusal).index(avail),
            "resolved_stamina": a.cost.resolve(u).stamina if False else
                                a.cost.stamina + (1 if a.cost.attack_surcharge else 0),
            "after": {"stamina": u.stamina, "ammo": u.ammo, "action_spent": u.action_spent},
            "before": {"stamina": before[0], "ammo": before[1], "action_spent": before[2]},
        })

    case("frenzy, plenty of stamina", "frenzy")
    case("frenzy, exactly enough", "frenzy", stamina=3)
    case("frenzy, one short", "frenzy", stamina=2)
    case("healing with ammo", "healing")
    case("healing without ammo", "healing", ammo=0)
    case("turtle after acting", "turtle", action_spent=True)
    case("turtle at zero stamina", "turtle", stamina=0)
    case("frenzy while tireless at zero", "frenzy", stamina=0, flags=["Неутомимый"])
    case("carrion eater, ordinary unit", "carrion_eater")
    case("carrion eater, ratman after acting", "carrion_eater",
         subtypes=["Крысолюд"], action_spent=True)
    case("forced march overspend floors at zero", "forced_march", stamina=2)
    case("shield bash surcharge", "shield_bash")
    return fx


def turn_fixture() -> dict:
    """Action-point cases, emphasising the re-entry semantics."""
    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "speed": [], "sequences": [], "initiative": []}

    for speed, stamina, flags in ((3, 10, []), (3, 4, []), (3, 3, []), (3, 2, []),
                                  (3, 0, []), (1, 0, []), (3, 0, ["Неутомимый"])):
        u = Combatant(speed=speed, stamina=stamina, stamina_base=10)
        u.flags = set(flags)
        fx["speed"].append({"speed": speed, "stamina": stamina, "flags": flags,
                            "expected": turn.effective_speed(u)[0]})

    def seq(label, steps, **kw):
        kw.setdefault("speed", 4)
        kw.setdefault("stamina", 10)
        kw.setdefault("stamina_base", 10)
        u = Combatant(name="u")
        flags = kw.pop("flags", [])
        for k, v in kw.items():
            setattr(u, k, v)
        u.flags = set(flags)
        turn.begin_round(u)
        for op, arg in steps:
            if op == "move":
                turn.spend_move(u, arg)
            elif op == "attack":
                turn.spend_attack(u)
            elif op == "rest":
                turn.rest(u)
            elif op == "new_round":
                turn.begin_round(u)
        fx["sequences"].append({
            "label": label, "setup": dict(kw, flags=flags), "steps": steps,
            "after": {"stamina": u.stamina, "movement_remaining": u.movement_remaining,
                      "steps_this_round": u.steps_this_round,
                      "action_spent": u.action_spent, "forced_rest": u.forced_rest,
                      "resting": u.resting},
        })

    seq("attack in place", [("attack", 0)])
    seq("move then attack", [("move", 1), ("attack", 0)])
    seq("out and back, then attack", [("move", 2), ("move", 2), ("attack", 0)])
    seq("split movement across a yield", [("move", 1), ("move", 1)])
    seq("act then keep moving", [("move", 1), ("attack", 0), ("move", 1)])
    seq("rest with recovery", [("rest", 0)], stamina=4, stamina_recovery=2)
    seq("rest caps at base", [("rest", 0)], stamina=9, stamina_recovery=5)
    seq("Зуд suppresses recovery", [("rest", 0)], stamina=4, stamina_recovery=3,
        flags=["Зуд"])
    seq("exhaustion forces next round", [("move", 1), ("attack", 0), ("new_round", 0)],
        stamina=2, stamina_recovery=1)
    seq("tireless pays nothing", [("move", 2), ("attack", 0)], stamina=1,
        flags=["Неутомимый"])

    # extra turns
    fx["extra_turns"] = []

    def extra(label, steps, **kw):
        kw.setdefault("speed", 3)
        kw.setdefault("stamina", 10)
        kw.setdefault("stamina_base", 10)
        u = Combatant(name="u")
        flags = kw.pop("flags", [])
        for k, v in kw.items():
            setattr(u, k, v)
        u.flags = set(flags)
        turn.begin_round(u)
        granted = []
        for op, arg in steps:
            if op == "move":
                turn.spend_move(u, arg)
            elif op == "attack":
                turn.spend_attack(u)
            elif op == "rest":
                turn.rest(u)
            elif op == "new_round":
                turn.begin_round(u)
            elif op == "extra":
                g, _ = turn.grant_extra_turn(u)
                granted.append(g)
            elif op == "extra_rs":
                g, _ = turn.grant_extra_turn(u, fire_round_start=True)
                granted.append(g)
            elif op == "extra_once":
                g, _ = turn.grant_extra_turn(u, source=arg, once_per_round=True)
                granted.append(g)
        fx["extra_turns"].append({
            "label": label, "setup": dict(kw, flags=flags), "steps": steps,
            "granted": granted,
            "after": {"stamina": u.stamina, "movement_remaining": u.movement_remaining,
                      "steps_this_round": u.steps_this_round,
                      "action_spent": u.action_spent, "forced_rest": u.forced_rest,
                      "resting": u.resting},
        })

    extra("plain extra turn restores movement and action",
          [("move", 3), ("attack", 0), ("extra", 0)])
    extra("steps survive the extra turn",
          [("move", 2), ("extra", 0), ("attack", 0)])
    extra("resting persists through an extra turn",
          [("rest", 0), ("extra", 0)], stamina=4, stamina_recovery=1)
    extra("once-per-round source fires only once",
          [("extra_once", "Кровавое безумие"), ("attack", 0),
           ("extra_once", "Кровавое безумие")])
    extra("a different source is tracked separately",
          [("extra_once", "Кровавое безумие"), ("extra_once", "Азарт Охотника")])
    extra("limiter clears only at a true round start",
          [("extra_once", "Кровавое безумие"), ("new_round", 0),
           ("extra_once", "Кровавое безумие")])
    extra("resources-only grant leaves the forced rest pending",
          [("move", 1), ("attack", 0), ("extra", 0)], stamina=2, stamina_recovery=1)
    extra("round-start grant serves the forced rest",
          [("move", 1), ("attack", 0), ("extra_rs", 0)], stamina=2, stamina_recovery=1)

    for a_init, b_init, a_attacker, want in ((3, 5, True, 1), (5, 3, True, 0),
                                             (3, 3, True, 0), (3, 3, False, 1)):
        fx["initiative"].append({"a": a_init, "b": b_init, "a_attacker": a_attacker,
                                 "expected": want})
    return fx


def content_fixture() -> dict:
    """Synthetic packs exercising each failure kind, plus the per-pack
    disagreement that is the whole reason bindings exist."""
    packs = {
        "clean": {"1": {"name": "a", "hook": "STAT_PASSIVE", "handler": "h1", "uses": 3},
                  "2": {"name": "b", "hook": "ON_HIT", "handler": "h2", "uses": 1}},
        "holed": {"1": {"name": "bound", "hook": "STAT_PASSIVE", "handler": "h1", "uses": 5},
                  "2": {"name": "empty", "hook": "STAT_PASSIVE", "handler": "", "uses": 9},
                  "3": {"name": "typo", "hook": "ON_HIT", "handler": "nonexistent", "uses": 1},
                  "4": {"name": "empty2", "hook": "AURA", "handler": "", "uses": 2}},
        "genesis_like": {"30": {"name": "Иммунитет к магии",
                                "handler": "magic_immunity", "uses": 1}},
        "nh_like": {"30": {"name": "Бронебойный удар",
                           "handler": "armor_pierce", "uses": 1}},
    }
    handlers = ["h1", "h2", "magic_immunity", "armor_pierce", "unused"]

    import tempfile, os as _os, json as _json
    expected = {}
    with tempfile.TemporaryDirectory() as tmp:
        for pid, abilities in packs.items():
            d = _os.path.join(tmp, pid)
            _os.makedirs(d)
            with open(_os.path.join(d, "bindings.json"), "w", encoding="utf-8") as fh:
                _json.dump({"pack": pid, "abilities": abilities}, fh, ensure_ascii=False)
            reg = content_mod.AbilityRegistry()
            for h in handlers:
                reg.register(h, lambda ctx, v, p: v)
            db = content_mod.ContentDb.load(pid, d, reg)
            r = db.report
            expected[pid] = {
                "total": r.total, "bound": r.bound, "usable": r.usable,
                "unbound": [list(x) for x in r.unbound],
                "missing": [list(x) for x in r.missing],
                "orphaned": r.orphaned, "ok": r.ok,
                "resolve": {k: list(db.resolve(int(k))) if db.resolve(int(k))[0]
                            else ["", {}] for k in abilities},
            }
    return {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
            "handlers": handlers, "packs": packs, "expected": expected}


def battlefield_fixture() -> dict:
    """Grid facts, range counts, and — the part that matters — exact paths.

    Paths are recorded as coordinate lists so the port cannot merely produce a
    path of the right LENGTH; it must produce the same one, hex for hex. Equal-
    cost routes are common on open ground, so a tie-break difference between the
    two implementations would show up here and nowhere else until replays
    started diverging.
    """
    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "dimensions": [], "range": [], "paths": [], "reachable": [], "lines": []}

    for w, h in ((1, 1), (7, 7), (3, 11), (20, 4)):
        fx["dimensions"].append({"width": w, "height": h, "tiles": w * h})

    bf = bfmod.Battlefield(11, 11)
    c = bfmod.offset_to_axial(5, 5)
    for radius in (0, 1, 2, 3, 4):
        fx["range"].append({"width": 11, "height": 11, "centre": [5, 5],
                            "radius": radius,
                            "within": len(bf.within(c, radius)),
                            "ring": len(bf.ring(c, radius))})

    def path_case(label, w, h, a, b, walls=(), occupied=(), ignore=False):
        grid = bfmod.Battlefield(w, h)
        for col, row in walls:
            grid.tile(bfmod.offset_to_axial(col, row)).move_cost = 0
        for col, row in occupied:
            grid.place(object(), bfmod.offset_to_axial(col, row))
        p = grid.path(bfmod.offset_to_axial(*a), bfmod.offset_to_axial(*b),
                      ignore_occupants=ignore)
        fx["paths"].append({
            "label": label, "width": w, "height": h, "from": list(a), "to": list(b),
            "walls": [list(x) for x in walls], "occupied": [list(x) for x in occupied],
            "ignore_occupants": ignore,
            "path": [list(bfmod.axial_to_offset(x)) for x in p] if p is not None else None,
        })

    path_case("open ground", 7, 7, (0, 0), (4, 0))
    path_case("diagonal across an open field", 9, 9, (0, 0), (6, 4))
    path_case("detour around a wall", 7, 7, (0, 0), (4, 0),
              walls=[(2, r) for r in range(6)])
    path_case("no route through a full wall", 5, 5, (0, 0), (4, 4),
              walls=[(2, r) for r in range(5)])
    path_case("a unit blocks the corridor", 5, 1, (0, 0), (4, 0), occupied=[(2, 0)])
    path_case("ignoring occupants clears it", 5, 1, (0, 0), (4, 0),
              occupied=[(2, 0)], ignore=True)
    path_case("path to self", 5, 5, (2, 2), (2, 2))

    grid = bfmod.Battlefield(9, 9)
    c = bfmod.offset_to_axial(4, 4)
    fx["reachable"].append({"width": 9, "height": 9, "centre": [4, 4], "budget": 2,
                            "rough": [], "count": len(grid.reachable(c, 2))})
    rough = bfmod.Battlefield(9, 9)
    ring = [bfmod.axial_to_offset(x) for x in rough.neighbours(c)]
    for x in rough.neighbours(c):
        rough.tile(x).move_cost = 2
    fx["reachable"].append({"width": 9, "height": 9, "centre": [4, 4], "budget": 2,
                            "rough": [list(x) for x in ring],
                            "count": len(rough.reachable(c, 2))})

    grid = bfmod.Battlefield(9, 9)
    for a, b in (((0, 0), (4, 0)), ((0, 0), (4, 4)), ((3, 1), (3, 1))):
        ln = grid.line(bfmod.offset_to_axial(*a), bfmod.offset_to_axial(*b))
        fx["lines"].append({"from": list(a), "to": list(b),
                            "line": [list(bfmod.axial_to_offset(x)) for x in ln]})
    return fx


def rng_fixture() -> dict:
    fx = {
        "note": "generated by oracle/make_fixtures.py — do not hand-edit",
        "seed": 42,
        "algorithm": "fnv1a-lcg-2^31",
        "streams": {},
        "fnv1a": {},
    }
    for stream, sides in (("attack", 100), ("chip", 6), ("combat", 20), ("level_up", 37)):
        r = Rng(fx["seed"])
        fx["streams"]["%s:%d" % (stream, sides)] = [r.roll(sides, stream) for _ in range(16)]
    for name in ("attack", "chip", "combat", "level_up", ""):
        fx["fnv1a"][name] = Rng.fnv1a(name)
    return fx


def write(path: str, payload: dict) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    print("wrote %s" % path)


if __name__ == "__main__":
    dest = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(dest, exist_ok=True)
    write(os.path.join(dest, "rng_fixture.json"), rng_fixture())
    write(os.path.join(dest, "pipeline_fixture.json"), out)
    write(os.path.join(dest, "action_fixture.json"), action_fixture())
    write(os.path.join(dest, "turn_fixture.json"), turn_fixture())
    write(os.path.join(dest, "content_fixture.json"), content_fixture())
    write(os.path.join(dest, "battlefield_fixture.json"), battlefield_fixture())
