"""Generate the cross-language fixtures the GDScript tests consume.

    python3 oracle/make_fixtures.py tests/fixtures/

Writes rng_fixture.json and pipeline_fixture.json.

COMMIT THE OUTPUT. Do not wire this into the test run. A fixture regenerated at
test time records whatever the code currently does, so the test can never fail
and reviews show no diff — the same class of defect as the RNG bug, where every
check passed while the property under test was broken. Regeneration must be a
deliberate act whose diff is reviewable: if a formula changes, the changed
expected values are exactly what a reviewer needs to see.

The RNG-free pipeline cases carry exact expected values and are meaningful
before the RNG port is confirmed. The RNG-dependent cases assume test_rng.gd
passes, so run that first.
"""
import json
import os
import sys

import combat
import actions
import turn
import content as content_mod
import battlefield as bfmod
import scenario as scenmod
import handlers as handlermod
import counterattack as camod
import statuses as stmod
import roster as rostermod
from modifier import Hook, Modifier, Pipeline
from combat import AttackKind, Combatant, Rng

KIND = {"melee": AttackKind.MELEE, "counter": AttackKind.COUNTER, "ranged": AttackKind.RANGED}
KIND_ORD = {"melee": 0, "counter": 1, "ranged": 2}


def make(**kw):
    c = Combatant()
    for k, v in kw.items():
        if k == "flags":
            c.flags = set(v)
        else:
            setattr(c, k, v)
    return c


CASES = [
    ("healthy melee",            dict(name="a", attack=8, life_base=17, life=17), "melee"),
    ("additive bonus only",      dict(name="a", attack=8, attack_bonus=3, life_base=17, life=17), "melee"),
    ("wounded",                  dict(name="a", attack=8, life_base=17, life=5), "melee"),
    ("wounded + painless",       dict(name="a", attack=8, life_base=17, life=5,
                                      flags=["Не чувствует боли"]), "melee"),
    ("low stamina",              dict(name="a", attack=10, stamina=3, life_base=20, life=20), "melee"),
    ("zero stamina",             dict(name="a", attack=10, stamina=0, life_base=20, life=20), "melee"),
    ("zero stamina + tireless",  dict(name="a", attack=10, stamina=0, life_base=20, life=20,
                                      flags=["Неутомимый"]), "melee"),
    ("all three multipliers",    dict(name="a", attack=12, attack_bonus=2, stamina=2,
                                      life_base=30, life=6, morale=10, morale_base=10), "melee"),
    ("rage suppresses wound",    dict(name="a", attack=12, life_base=30, life=6,
                                      flags=["Боевое безумие"]), "melee"),
    ("counter attack stat",      dict(name="a", counter_attack=6, life_base=17, life=17), "counter"),
    ("ranged attack stat",       dict(name="a", ranged_attack=7, life_base=17, life=17), "ranged"),
]

DEF_CASES = [
    ("plain defence",        dict(name="d", defence=5, ranged_defence=7), "melee"),
    ("plain ranged defence", dict(name="d", defence=5, ranged_defence=7), "ranged"),
    ("defence bonus",        dict(name="d", defence=5, defence_bonus=3), "melee"),
    ("exhausted halving",    dict(name="d", defence=7, ranged_defence=9, stamina=0), "melee"),
    ("exhausted ranged",     dict(name="d", defence=7, ranged_defence=9, stamina=0), "ranged"),
    ("exhausted odd floor",  dict(name="d", defence=1, stamina=0), "melee"),
    ("exhausted tireless",   dict(name="d", defence=7, stamina=0, flags=["Неутомимый"]), "melee"),
]

out = {
    "note": "generated by oracle/make_fixtures.py — do not hand-edit",
    "attack_value": [],
    "defence_value": [],
    "multipliers": {"wound": [], "stamina": [], "morale": []},
    "morale_attack": [],
    "attack_entry": [],
    "defence_tail": [],
    "conditional_attack_power": [],
    "capacity_cost": [],
    "roll_attack": [],
    "resolve": [],
}

for label, kw, kind in CASES:
    c = make(**kw)
    v, _ = combat.current_attack(c, KIND[kind])
    out["attack_value"].append({
        "label": label, "kind": KIND_ORD[kind], "unit": kw, "expected": round(v, 6),
    })

for label, kw, kind in DEF_CASES:
    c = make(**kw)
    v, _ = combat.current_defence(c, KIND[kind])
    out["defence_value"].append({
        "label": label, "kind": KIND_ORD[kind], "unit": kw, "expected": v,
    })

for pct in (100, 60, 50, 49, 40, 30, 20, 10, 1):
    c = make(life_base=100, life=pct)
    out["multipliers"]["wound"].append({"life": pct, "life_base": 100,
                                        "expected": round(combat.wound_mod(c)[0], 6)})
for st in (10, 6, 5, 4, 3, 2, 1, 0):
    c = make(stamina=st)
    out["multipliers"]["stamina"].append({"stamina": st,
                                          "expected": round(combat.stamina_mod(c)[0], 6)})
# Morale is keyed on ABSOLUTE morale, so morale_base is varied independently to
# prove it does not enter the multiplier. Covers the panic floor, every point of
# the low band, the neutral band edges, and the first band boundaries above 15 —
# 16/18/21 are exactly the transitions OPEN_QUESTIONS item 1 must confirm for
# the Genesis build.
for mo in (0, 1, 2, 3, 4, 5, 6, 10, 15, 16, 17, 18, 20, 21, 24, 25, 29, 30, 35,
           36, 42, 43, 50, 51):
    c = make(morale=mo, morale_base=10)
    out["multipliers"]["morale"].append({"morale": mo, "morale_base": 10,
                                         "expected": round(combat.morale_mod(c)[0], 6)})

# Whole-stat vectors through current_attack(). These are the ones that catch the
# integer truncation: the binary applies morale as a whole-percent bonus to an
# integer, so a float multiplier diverges (100 * 1.15 == 114.999... -> 114 where
# the executable returns 115). Bases are chosen so the percentage lands just
# under, just over, and exactly on an integer boundary.
# base 0 and 1 exercise the min-1 clamp: 2 Genesis and 22 NH units have
# Attack 0, and attack 1 under the stamina-0 halving truncates to 0.
# R8: the attack stamina cost keys on LIVE remaining capacity versus effective
# speed, with a strict less-than — not on movement history. Capacity equal to or
# above effective speed costs 1, including the restored-capacity case that the
# old `steps_this_round > 0` rule charged 2 for.
for speed in (1, 2, 3, 5):
    for stamina in (0, 2, 3, 4, 5, 10):
        for capacity in (0, 1, 2, 3, 5, 9):
            c = make(speed=speed, stamina=stamina, stamina_base=10)
            c.movement_remaining = capacity
            c.steps_this_round = 3          # deliberately nonzero: must not matter
            out["capacity_cost"].append({
                "speed": speed, "stamina": stamina, "capacity": capacity,
                "effective_speed": turn.effective_speed(c)[0],
                "expected": turn.attack_stamina_cost(c),
            })

# R6 entry semantics: the three attack kinds differ BEFORE the shared tail.
# Melee/counter return 0 under modifier 0x26; ranged returns 0 on a zero sum
# without ever reaching the minimum-one clamp.
for base in (0, 1, 7):
    for no_fight in (False, True):
        for kind in ("melee", "counter", "ranged"):
            c = make(attack=base, counter_attack=base, ranged_attack=base,
                     morale=10, morale_base=10)
            if no_fight:
                c.flags.add("Не сражается")
            v, _ = combat.current_attack(c, KIND[kind])
            out["attack_entry"].append({
                "base": base, "no_fight": no_fight, "kind": KIND_ORD[kind],
                "expected": int(v),
            })

# R10 accepted stage vectors. Expected powers are copied from the frozen
# compatibility matrix, not generated from current implementation output.
R10_CASES = [
    ("healthy", {"attack": 20, "life_base": 100, "life": 100,
                 "stamina": 10, "morale": 10, "conditional_bonus": 5},
     "melee", False, 25),
    ("25 percent life", {"attack": 20, "life_base": 100, "life": 25,
                         "stamina": 10, "morale": 10,
                         "conditional_bonus": 5},
     "melee", False, 20),
    ("zero stamina", {"attack": 20, "life_base": 100, "life": 100,
                       "stamina": 0, "morale": 10,
                       "conditional_bonus": 5},
     "melee", False, 13),
    ("zero morale", {"attack": 20, "life_base": 100, "life": 100,
                      "stamina": 10, "morale": 0,
                      "conditional_bonus": 5},
     "melee", False, 13),
    ("selected ordinary 1.5x", {"attack": 20, "life_base": 100,
                                 "life": 100, "stamina": 10, "morale": 10,
                                 "conditional_bonus": 5},
     "melee", True, 35),
    ("counterattack", {"counter_attack": 20, "life_base": 100, "life": 100,
                        "stamina": 10, "morale": 10,
                        "conditional_bonus": 5},
     "counter", False, 25),
    ("ranged exclusion", {"ranged_attack": 20, "life_base": 100, "life": 100,
                           "stamina": 10, "morale": 10,
                           "conditional_bonus": 5},
     "ranged", False, 20),
]
for label, unit, kind, selected, expected in R10_CASES:
    out["conditional_attack_power"].append({
        "label": label, "unit": unit, "kind": KIND_ORD[kind],
        "selected_ordinary_1_5x": selected, "expected": expected,
    })


# R9 defence tail: halve at EXACTLY zero stamina, then clamp to zero. Negative
# and odd values distinguish halve-then-clamp from clamp-then-halve, and
# stamina -1 checks that the predicate is equality rather than <= 0.
for value in (-3, -1, 0, 1, 2, 3, 7):
    for stamina in (10, 1, 0, -1):
        c = make(defence=value, ranged_defence=value, stamina=stamina)
        for kind in ("melee", "ranged"):
            d, _ = combat.current_defence(c, KIND[kind])
            out["defence_tail"].append({
                "value": value, "stamina": stamina, "kind": KIND_ORD[kind],
                "expected": int(d),
            })

for base in (0, 1, 7, 19, 20, 100):
    for mo in (0, 3, 5, 15, 16, 18, 21, 25, 30, 43, 51, 60):
        c = make(attack=base, counter_attack=base, ranged_attack=base,
                 morale=mo, morale_base=999)
        for kind in ("melee", "counter", "ranged"):
            v, _ = combat.current_attack(c, KIND[kind])
            out["morale_attack"].append({
                "base": base, "morale": mo, "kind": KIND_ORD[kind],
                "expected": int(v),
            })

# RNG-dependent: exact sequences given a fixed seed
for attack in (1, 3, 5, 8, 13, 37):
    r = Rng(1234)
    out["roll_attack"].append({
        "attack": attack, "seed": 1234,
        "expected": [combat.roll_attack(attack, r)[0] for _ in range(12)],
    })

r = Rng(99)
seq = []
atk = make(name="Мечник", attack=8, attack_bonus=2, life_base=17, life=5, stamina=3)
dfn = make(name="Ополченец", defence=3, life_base=12, life=12)
for _ in range(10):
    d, _tr = combat.resolve_attack(atk, dfn, AttackKind.MELEE, r)
    seq.append(d)
out["resolve"].append({
    "label": "wounded exhausted swordsman vs militia", "seed": 99,
    "attacker": dict(name="Мечник", attack=8, attack_bonus=2, life_base=17, life=5, stamina=3),
    "defender": dict(name="Ополченец", defence=3, life_base=12, life=12),
    "kind": 0, "expected": seq,
})

def action_fixture() -> dict:
    """The catalogue plus decidable legality/cost cases.

    The catalogue is exported so the GDScript side builds Actions from data
    rather than duplicating a hardcoded list — which exists are content and
    differ per pack.
    """
    fx = {
        "note": "generated by oracle/make_fixtures.py — do not hand-edit",
        "catalogue": [],
        "cases": [],
    }
    for a in actions.CATALOGUE.values():
        fx["catalogue"].append({
            "id": a.id, "name": a.name, "target": list(actions.Target).index(a.target),
            "cost_stamina": a.cost.stamina, "cost_ammo": a.cost.ammo,
            "consumes_action": a.cost.consumes_action,
            "attack_surcharge": a.cost.attack_surcharge,
            "free_action_for": list(a.cost.free_action_for),
            "magnitude": a.magnitude, "is_attack": a.is_attack,
            "damage_scale": a.damage_scale,
            "suppresses": list(a.suppresses),
            "scales": [list(p) for p in a.scales],
            "excluded_targets": list(a.excluded_targets),
            "suppresses_counterattack": a.suppresses_counterattack,
            # grants were omitted here, so the port's catalogue silently had
            # none: Action.from_dict reads them, the generator never emitted
            # them, and the two grant-bearing actions (turtle, forced_march)
            # arrived in GDScript with empty grants.
            "grants": [list(g) for g in a.grants],
            "notes": a.notes,
        })

    def case(label, action_id, **actor_kw):
        u = Combatant()
        u.stamina, u.stamina_base, u.ammo = 10, 10, 4
        for k, v in actor_kw.items():
            if k in ("flags", "subtypes"):
                setattr(u, k, set(v))
            else:
                setattr(u, k, v)
        a = actions.CATALOGUE[action_id]
        before = (u.stamina, u.ammo, u.action_spent)
        avail = a.availability(u)
        if avail is actions.Refusal.OK:
            a.pay(u)
        fx["cases"].append({
            "label": label, "action": action_id,
            "actor": {k: (sorted(v) if isinstance(v, set) else v)
                      for k, v in actor_kw.items()},
            "availability": list(actions.Refusal).index(avail),
            "resolved_stamina": a.cost.resolve(u).stamina if False else
                                a.cost.stamina + (1 if a.cost.attack_surcharge else 0),
            "after": {"stamina": u.stamina, "ammo": u.ammo, "action_spent": u.action_spent},
            "before": {"stamina": before[0], "ammo": before[1], "action_spent": before[2]},
        })

    case("frenzy, plenty of stamina", "frenzy")
    case("frenzy, exactly enough", "frenzy", stamina=3)
    case("frenzy, one short", "frenzy", stamina=2)
    case("healing with ammo", "healing")
    case("healing without ammo", "healing", ammo=0)
    case("turtle after acting", "turtle", action_spent=True)
    case("turtle at zero stamina", "turtle", stamina=0)
    case("frenzy while tireless at zero", "frenzy", stamina=0, flags=["Неутомимый"])
    case("carrion eater, ordinary unit", "carrion_eater")
    case("carrion eater, ratman after acting", "carrion_eater",
         subtypes=["Крысолюд"], action_spent=True)
    case("forced march overspend floors at zero", "forced_march", stamina=2)
    case("shield bash surcharge", "shield_bash")
    return fx


def turn_fixture() -> dict:
    """Action-point cases, emphasising the re-entry semantics."""
    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "speed": [], "sequences": [], "initiative": []}

    for speed, stamina, flags in ((3, 10, []), (3, 4, []), (3, 3, []), (3, 2, []),
                                  (3, 0, []), (1, 0, []), (3, 0, ["Неутомимый"])):
        u = Combatant(speed=speed, stamina=stamina, stamina_base=10)
        u.flags = set(flags)
        fx["speed"].append({"speed": speed, "stamina": stamina, "flags": flags,
                            "expected": turn.effective_speed(u)[0]})

    def seq(label, steps, **kw):
        kw.setdefault("speed", 4)
        kw.setdefault("stamina", 10)
        kw.setdefault("stamina_base", 10)
        u = Combatant(name="u")
        flags = kw.pop("flags", [])
        for k, v in kw.items():
            setattr(u, k, v)
        u.flags = set(flags)
        turn.begin_round(u)
        for op, arg in steps:
            if op == "move":
                turn.spend_move(u, arg)
            elif op == "attack":
                turn.spend_attack(u)
            elif op == "rest":
                turn.rest(u)
            elif op == "new_round":
                turn.begin_round(u)
        fx["sequences"].append({
            "label": label, "setup": dict(kw, flags=flags), "steps": steps,
            "after": {"stamina": u.stamina, "movement_remaining": u.movement_remaining,
                      "steps_this_round": u.steps_this_round,
                      "action_spent": u.action_spent, "forced_rest": u.forced_rest,
                      "resting": u.resting},
        })

    seq("attack in place", [("attack", 0)])
    seq("move then attack", [("move", 1), ("attack", 0)])
    seq("out and back, then attack", [("move", 2), ("move", 2), ("attack", 0)])
    seq("split movement across a yield", [("move", 1), ("move", 1)])
    seq("act then keep moving", [("move", 1), ("attack", 0), ("move", 1)])
    seq("rest with recovery", [("rest", 0)], stamina=4, stamina_recovery=2)
    seq("rest caps at base", [("rest", 0)], stamina=9, stamina_recovery=5)
    seq("Зуд suppresses recovery", [("rest", 0)], stamina=4, stamina_recovery=3,
        flags=["Зуд"])
    seq("exhaustion forces next round", [("move", 1), ("attack", 0), ("new_round", 0)],
        stamina=2, stamina_recovery=1)
    seq("tireless pays nothing", [("move", 2), ("attack", 0)], stamina=1,
        flags=["Неутомимый"])

    # extra turns
    fx["extra_turns"] = []

    def extra(label, steps, **kw):
        kw.setdefault("speed", 3)
        kw.setdefault("stamina", 10)
        kw.setdefault("stamina_base", 10)
        u = Combatant(name="u")
        flags = kw.pop("flags", [])
        for k, v in kw.items():
            setattr(u, k, v)
        u.flags = set(flags)
        turn.begin_round(u)
        granted = []
        for op, arg in steps:
            if op == "move":
                turn.spend_move(u, arg)
            elif op == "attack":
                turn.spend_attack(u)
            elif op == "rest":
                turn.rest(u)
            elif op == "new_round":
                turn.begin_round(u)
            elif op == "extra":
                g, _ = turn.grant_extra_turn(u)
                granted.append(g)
            elif op == "extra_rs":
                g, _ = turn.grant_extra_turn(u, fire_round_start=True)
                granted.append(g)
            elif op == "extra_once":
                g, _ = turn.grant_extra_turn(u, source=arg, once_per_round=True)
                granted.append(g)
        fx["extra_turns"].append({
            "label": label, "setup": dict(kw, flags=flags), "steps": steps,
            "granted": granted,
            "after": {"stamina": u.stamina, "movement_remaining": u.movement_remaining,
                      "steps_this_round": u.steps_this_round,
                      "action_spent": u.action_spent, "forced_rest": u.forced_rest,
                      "resting": u.resting},
        })

    extra("plain extra turn restores movement and action",
          [("move", 3), ("attack", 0), ("extra", 0)])
    extra("steps survive the extra turn",
          [("move", 2), ("extra", 0), ("attack", 0)])
    extra("resting persists through an extra turn",
          [("rest", 0), ("extra", 0)], stamina=4, stamina_recovery=1)
    extra("once-per-round source fires only once",
          [("extra_once", "Кровавое безумие"), ("attack", 0),
           ("extra_once", "Кровавое безумие")])
    extra("a different source is tracked separately",
          [("extra_once", "Кровавое безумие"), ("extra_once", "Азарт Охотника")])
    extra("limiter clears only at a true round start",
          [("extra_once", "Кровавое безумие"), ("new_round", 0),
           ("extra_once", "Кровавое безумие")])
    extra("resources-only grant leaves the forced rest pending",
          [("move", 1), ("attack", 0), ("extra", 0)], stamina=2, stamina_recovery=1)
    extra("round-start grant serves the forced rest",
          [("move", 1), ("attack", 0), ("extra_rs", 0)], stamina=2, stamina_recovery=1)

    for a_init, b_init, a_attacker, want in ((3, 5, True, 1), (5, 3, True, 0),
                                             (3, 3, True, 0), (3, 3, False, 1)):
        fx["initiative"].append({"a": a_init, "b": b_init, "a_attacker": a_attacker,
                                 "expected": want})
    return fx


def content_fixture() -> dict:
    """Synthetic packs exercising each failure kind, plus the per-pack
    disagreement that is the whole reason bindings exist."""
    packs = {
        "clean": {"1": {"name": "a", "hook": "STAT_PASSIVE", "handler": "h1", "uses": 3},
                  "2": {"name": "b", "hook": "ON_HIT", "handler": "h2", "uses": 1}},
        "holed": {"1": {"name": "bound", "hook": "STAT_PASSIVE", "handler": "h1", "uses": 5},
                  "2": {"name": "empty", "hook": "STAT_PASSIVE", "handler": "", "uses": 9},
                  "3": {"name": "typo", "hook": "ON_HIT", "handler": "nonexistent", "uses": 1},
                  "4": {"name": "empty2", "hook": "AURA", "handler": "", "uses": 2}},
        "genesis_like": {"30": {"name": "Иммунитет к магии",
                                "handler": "magic_immunity", "uses": 1}},
        "nh_like": {"30": {"name": "Бронебойный удар",
                           "handler": "armor_pierce", "uses": 1}},
    }
    handlers = ["h1", "h2", "magic_immunity", "armor_pierce", "unused"]

    import tempfile, os as _os, json as _json
    expected = {}
    with tempfile.TemporaryDirectory() as tmp:
        for pid, abilities in packs.items():
            d = _os.path.join(tmp, pid)
            _os.makedirs(d)
            with open(_os.path.join(d, "bindings.json"), "w", encoding="utf-8") as fh:
                _json.dump({"pack": pid, "abilities": abilities}, fh, ensure_ascii=False)
            reg = content_mod.AbilityRegistry()
            for h in handlers:
                reg.register(h, lambda ctx, v, p: v)
            db = content_mod.ContentDb.load(pid, d, reg)
            r = db.report
            expected[pid] = {
                "total": r.total, "bound": r.bound, "usable": r.usable,
                "unbound": [list(x) for x in r.unbound],
                "missing": [list(x) for x in r.missing],
                "orphaned": r.orphaned, "ok": r.ok,
                "resolve": {k: list(db.resolve(int(k))) if db.resolve(int(k))[0]
                            else ["", {}] for k in abilities},
            }
    return {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
            "handlers": handlers, "packs": packs, "expected": expected}


def battlefield_fixture() -> dict:
    """Grid facts, range counts, and — the part that matters — exact paths.

    Paths are recorded as coordinate lists so the port cannot merely produce a
    path of the right LENGTH; it must produce the same one, hex for hex. Equal-
    cost routes are common on open ground, so a tie-break difference between the
    two implementations would show up here and nowhere else until replays
    started diverging.
    """
    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "dimensions": [], "range": [], "paths": [], "reachable": [], "lines": []}

    for w, h in ((1, 1), (7, 7), (3, 11), (20, 4)):
        fx["dimensions"].append({"width": w, "height": h, "tiles": w * h})

    bf = bfmod.Battlefield(11, 11)
    c = bfmod.offset_to_axial(5, 5)
    for radius in (0, 1, 2, 3, 4):
        fx["range"].append({"width": 11, "height": 11, "centre": [5, 5],
                            "radius": radius,
                            "within": len(bf.within(c, radius)),
                            "ring": len(bf.ring(c, radius))})

    def path_case(label, w, h, a, b, walls=(), occupied=(), ignore=False):
        grid = bfmod.Battlefield(w, h)
        for col, row in walls:
            grid.tile(bfmod.offset_to_axial(col, row)).move_cost = 0
        for col, row in occupied:
            grid.place(object(), bfmod.offset_to_axial(col, row))
        p = grid.path(bfmod.offset_to_axial(*a), bfmod.offset_to_axial(*b),
                      ignore_occupants=ignore)
        fx["paths"].append({
            "label": label, "width": w, "height": h, "from": list(a), "to": list(b),
            "walls": [list(x) for x in walls], "occupied": [list(x) for x in occupied],
            "ignore_occupants": ignore,
            "path": [list(bfmod.axial_to_offset(x)) for x in p] if p is not None else None,
        })

    path_case("open ground", 7, 7, (0, 0), (4, 0))
    path_case("diagonal across an open field", 9, 9, (0, 0), (6, 4))
    path_case("detour around a wall", 7, 7, (0, 0), (4, 0),
              walls=[(2, r) for r in range(6)])
    path_case("no route through a full wall", 5, 5, (0, 0), (4, 4),
              walls=[(2, r) for r in range(5)])
    path_case("a unit blocks the corridor", 5, 1, (0, 0), (4, 0), occupied=[(2, 0)])
    path_case("ignoring occupants clears it", 5, 1, (0, 0), (4, 0),
              occupied=[(2, 0)], ignore=True)
    path_case("path to self", 5, 5, (2, 2), (2, 2))

    grid = bfmod.Battlefield(9, 9)
    c = bfmod.offset_to_axial(4, 4)
    fx["reachable"].append({"width": 9, "height": 9, "centre": [4, 4], "budget": 2,
                            "rough": [], "count": len(grid.reachable(c, 2))})
    rough = bfmod.Battlefield(9, 9)
    ring = [bfmod.axial_to_offset(x) for x in rough.neighbours(c)]
    for x in rough.neighbours(c):
        rough.tile(x).move_cost = 2
    fx["reachable"].append({"width": 9, "height": 9, "centre": [4, 4], "budget": 2,
                            "rough": [list(x) for x in ring],
                            "count": len(rough.reachable(c, 2))})

    grid = bfmod.Battlefield(9, 9)
    for a, b in (((0, 0), (4, 0)), ((0, 0), (4, 4)), ((3, 1), (3, 1))):
        ln = grid.line(bfmod.offset_to_axial(*a), bfmod.offset_to_axial(*b))
        fx["lines"].append({"from": list(a), "to": list(b),
                            "line": [list(bfmod.axial_to_offset(x)) for x in ln]})
    return fx


def scenario_fixture() -> dict:
    """Expected logs for every scenario in tests/scenarios/.

    The log is the artifact, not the final state: two implementations that
    disagree about a pathfinding tie-break or about when stamina is charged can
    still reach the same final state by a different route. The log localises the
    divergence to the line where it happens.
    """
    import glob
    out = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
           "scenarios": {}}
    for path in sorted(glob.glob("tests/scenarios/*.json")) or \
                sorted(glob.glob("scenarios/*.json")):
        with open(path, encoding="utf-8") as fh:
            spec = json.load(fh)
        result = scenmod.Scenario(json.loads(json.dumps(spec))).run()
        out["scenarios"][os.path.basename(path)] = {
            "spec": spec, "log": result["log"], "final": result["final"],
        }
    return out


def scenario_content_fixture() -> dict:
    """Project-authored pack definitions for canonical-scenario parity."""
    definitions = {
        "synthetic:unit/5": {
            "name": "Synthetic vanguard",
            "attack": 6, "counter_attack": 2,
            "ranged_attack": 0, "shooting_range": 0,
            "defence": 1, "ranged_defence": 1, "resist": 0,
            "life": 15, "stamina": 7, "morale": 10, "speed": 4,
            "ammo": 0,
            "flags": ["synthetic_flag"],
            "subtypes": ["synthetic_subtype"],
            "modifiers": [{
                "ability": 9001, "handler": "stat_delta",
                "hook": "STAT_PASSIVE", "power": 1,
                "params": {"stat": "attack", "nested": {"order": [2, 1]}},
                "source": "synthetic attack",
            }],
            "auras": [{
                "id": "synthetic-aura", "scope": "ADJACENT",
                "affects": "ALLY", "stacking": "MAXIMUM", "power": 0,
                "only_subtypes": ["synthetic_subtype"],
                "modifiers": [],
            }],
        },
    }
    provider = content_mod.ScenarioContentProvider(
        "synthetic", definitions, version="fixture-v1", build="fixture-build-7")
    canonical = {
        "name": "content-backed synthetic", "profile": "native", "seed": 23,
        "content": provider.content_provenance(),
        "battlefield": {"width": 5, "height": 3, "tiles": []},
        "sides": [
            {"id": 0, "is_attacker": True, "leader_initiative": 1,
             "units": [{"id": "attacker-1", "def": "synthetic:unit/5",
                        "at": [0, 0], "overrides": {"stamina": 4}}]},
            {"id": 1, "leader_initiative": 0, "units": [{
                "id": "target-1", "name": "Synthetic target", "at": [2, 0],
                "attack": 0, "counter_attack": 0, "defence": 0,
                "ranged_defence": 0, "life": 30, "stamina": 10,
                "morale": 10, "speed": 1,
            }]},
        ],
        "commands": [{"op": "attack", "unit": "attacker-1", "target": "target-1"}],
    }
    inline = json.loads(json.dumps(canonical))
    inline.pop("content")
    inline_unit = json.loads(json.dumps(definitions["synthetic:unit/5"]))
    inline_unit.update({"id": "attacker-1", "at": [0, 0], "stamina": 4})
    inline["sides"][0]["units"][0] = inline_unit

    canonical_scenario = scenmod.Scenario(
        json.loads(json.dumps(canonical)), content_provider=provider)
    canonical_unit = canonical_scenario.units["attacker-1"]
    canonical_result = canonical_scenario.run()
    inline_result = scenmod.Scenario(json.loads(json.dumps(inline))).run()
    return {
        "note": "generated by oracle/make_fixtures.py — synthetic content only",
        "provider": {
            "pack": "synthetic", "version": "fixture-v1",
            "build": "fixture-build-7",
            "fingerprint": provider.fingerprint,
            "definitions": definitions,
        },
        "canonical_spec": canonical,
        "inline_spec": inline,
        "expected": {
            "log": canonical_result["log"],
            "final": canonical_result["final"],
            "inline_log": inline_result["log"],
            "inline_final": inline_result["final"],
            "unit": {
                "name": canonical_unit.name,
                "instance_id": canonical_unit.instance_id,
                "content_id": canonical_unit.content_id,
                "life": canonical_unit.life,
                "life_base": canonical_unit.life_base,
                "stamina": canonical_unit.stamina,
                "stamina_base": canonical_unit.stamina_base,
                "morale": canonical_unit.morale,
                "morale_base": canonical_unit.morale_base,
                "flags": sorted(canonical_unit.flags),
                "subtypes": sorted(canonical_unit.subtypes),
                "modifier_params": canonical_unit.modifiers[0].params,
                "auras": len(canonical_scenario.auras_by_source[canonical_unit]),
            },
        },
    }


def modifier_fixture() -> dict:
    """Pipeline cases. The hook VALUES are exported too: the enum's numeric
    order is the resolution order, so a divergence there would silently reorder
    every battle."""
    reg = content_mod.AbilityRegistry()
    handlermod.register_all(reg)
    p = Pipeline(reg)

    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "hooks": {h.name: int(h) for h in Hook},
          "cases": []}

    def case(label, base, mods, hook, ctx, mode="resolve"):
        specs = [{"ability": m.ability, "handler": m.handler, "hook": int(m.hook),
                  "power": m.power, "params": m.params, "source": m.source}
                 for m in mods]
        if mode == "flag":
            expected = p.flag(mods, hook, ctx)
        else:
            expected = p.resolve(base, mods, hook, ctx)[0]
        fx["cases"].append({
            "label": label, "mode": mode, "base": base, "hook": int(hook),
            "mods": specs, "ctx": {k: v for k, v in ctx.items()
                                   if not hasattr(v, "__dict__")},
            "ctx_target_subtypes": sorted(getattr(ctx.get("target"), "subtypes", []))
                                   if ctx.get("target") is not None else None,
            "expected": expected,
        })

    m_atk = Modifier(ability=2, handler="stat_delta", hook=Hook.STAT_PASSIVE,
                     power=3, params={"stat": "attack"}, source="Атака")
    m_def = Modifier(ability=4, handler="stat_delta", hook=Hook.STAT_PASSIVE,
                     power=5, params={"stat": "defence"}, source="Защита")
    m_pierce = Modifier(ability=30, handler="armor_pierce",
                        hook=Hook.DEFENCE_APPLY, source="Бронебойный выстрел")
    m_unknown = Modifier(ability=99, handler="not_implemented",
                         hook=Hook.STAT_PASSIVE, power=5,
                         params={"stat": "attack"}, source="opcode 99")
    m_scale = Modifier(ability=7, handler="stat_scale", hook=Hook.DAMAGE_BASE,
                       power=50, params={"stat": "attack"}, source="+50%")

    case("stat_delta reaches its own stat", 8, [m_atk], Hook.STAT_PASSIVE,
         {"stat": "attack"})
    case("and leaves others alone", 5, [m_atk], Hook.STAT_PASSIVE,
         {"stat": "defence"})
    case("two deltas on the same stat sum", 10, [m_atk, m_def], Hook.STAT_PASSIVE,
         {"stat": "defence"})
    case("list order does not matter", 10, [m_def, m_atk], Hook.STAT_PASSIVE,
         {"stat": "defence"})
    case("unknown handler is skipped", 8, [m_unknown], Hook.STAT_PASSIVE,
         {"stat": "attack"})
    case("halving at its own later hook", 15, [m_pierce], Hook.DEFENCE_APPLY,
         {"stat": "defence"})
    case("percentage scale", 10, [m_scale], Hook.DAMAGE_BASE, {"stat": "attack"})
    case("no modifiers is identity", 12, [], Hook.STAT_PASSIVE, {"stat": "attack"})

    m_imm = Modifier(ability=60, handler="immunity", hook=Hook.STATUS_RESIST,
                     params={"against": "яд"}, source="Иммунитет к яду")
    case("immunity asserts for its school", False, [m_imm], Hook.STATUS_RESIST,
         {"against": "яд"}, mode="flag")
    case("and not for another", False, [m_imm], Hook.STATUS_RESIST,
         {"against": "огонь"}, mode="flag")
    case("no modifiers means no immunity", False, [], Hook.STATUS_RESIST,
         {"against": "яд"}, mode="flag")

    und = Combatant(name="skeleton")
    und.subtypes = {"Нежить"}
    living = Combatant(name="militia")
    m_vs = Modifier(ability=210, handler="bonus_vs_subtype",
                    hook=Hook.DAMAGE_VS_TARGET, power=4,
                    params={"subtype": "Нежить"}, source="Сокрушение зла")
    case("conditional bonus hits the named subtype", 10, [m_vs],
         Hook.DAMAGE_VS_TARGET, {"target": und})
    case("and nobody else", 10, [m_vs], Hook.DAMAGE_VS_TARGET, {"target": living})

    fx["spell_grants"] = {
        "mods": [{"ability": 2010, "handler": "grant_spell", "hook": int(Hook.STAT_PASSIVE),
                  "power": 0, "params": {"spell": "Сглаз"}, "source": "Заклятье"},
                 {"ability": 2011, "handler": "grant_spell", "hook": int(Hook.STAT_PASSIVE),
                  "power": 0, "params": {"spell": "Благословение"}, "source": "Заклятье"}],
        "expected": sorted(["Сглаз", "Благословение"]),
    }
    return fx


def counter_fixture() -> dict:
    """Refusal reasons and exchange ORDER.

    The order matters more than the numbers: a model that always resolves the
    counter after the attack passes every naive test and gets Первый удар
    exactly backwards.
    """
    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "reasons": {r.name: i for i, r in enumerate(camod.NoCounter)},
          "refusals": [], "exchanges": []}

    def mk(**kw):
        kw.setdefault("attack", 8)
        kw.setdefault("counter_attack", 6)
        kw.setdefault("defence", 0)
        kw.setdefault("life", 30)
        kw.setdefault("stamina", 10)
        c = Combatant(name=kw.pop("name", "u"))
        flags = kw.pop("flags", [])
        resting = kw.pop("resting", False)
        alive = kw.pop("alive", True)
        for k, v in kw.items():
            setattr(c, k, v)
        c.flags = set(flags)
        c.resting = resting
        c.alive = alive
        c.life_base = kw.get("life", 30)
        c.stamina_base = 10
        c.morale_base = 10
        return c

    def refusal(label, defender_kw, attacker_kw, kind, suppress=False):
        d, a = mk(**defender_kw), mk(**attacker_kw)
        action = None
        if suppress:
            class _A:
                suppresses_counterattack = True
            action = _A()
        r = camod.why_no_counter(d, a, kind, action)
        fx["refusals"].append({
            "label": label, "defender": defender_kw, "attacker": attacker_kw,
            "kind": int(kind.value == "ranged") * 2 if False else
                    {"melee": 0, "counter": 1, "ranged": 2}[kind.value],
            "suppress": suppress,
            "expected": list(camod.NoCounter).index(r),
            "expected_name": r.name,
        })

    K = AttackKind
    refusal("ordinary melee is answered", {}, {}, K.MELEE)
    refusal("a shot is not", {}, {}, K.RANGED)
    refusal("no counterattack value", {"counter_attack": 0}, {}, K.MELEE)
    refusal("exhausted", {"stamina": 0}, {}, K.MELEE)
    refusal("exhausted but Неутомимый", {"stamina": 0, "flags": ["Неутомимый"]},
            {}, K.MELEE)
    refusal("resting", {"resting": True}, {}, K.MELEE)
    refusal("Не сражается", {"flags": ["Не сражается"]}, {}, K.MELEE)
    refusal("already down", {"alive": False}, {}, K.MELEE)
    refusal("attacker has Ловкость", {}, {"flags": ["Ловкость"]}, K.MELEE)
    refusal("attacker has Касание вампира", {}, {"flags": ["Касание вампира"]},
            K.MELEE)
    refusal("suppressed by the action", {}, {}, K.MELEE, suppress=True)

    def exchange(label, attacker_kw, defender_kw, seed, kind=K.MELEE):
        a, d = mk(**attacker_kw), mk(**defender_kw)
        ex = camod.resolve(a, d, Rng(seed), kind)
        fx["exchanges"].append({
            "label": label, "attacker": attacker_kw, "defender": defender_kw,
            "seed": seed,
            "kind": {"melee": 0, "counter": 1, "ranged": 2}[kind.value],
            "order": [[w, dmg] for w, dmg in ex.order],
            "counter_first": ex.counter_first,
            "countered": ex.countered,
            "attacker_died": ex.attacker_died,
            "defender_died": ex.defender_died,
            "attack_damage": ex.attack_damage,
            "counter_damage": ex.counter_damage,
        })

    exchange("normal order", {}, {}, 1)
    exchange("first strike reorders", {}, {"flags": ["Первый удар"]}, 1)
    exchange("both first-strikers cancel", {"flags": ["Первый удар"]},
             {"flags": ["Первый удар"]}, 1)
    exchange("lethal first strike stops the attack", {"life": 1},
             {"counter_attack": 40, "flags": ["Первый удар"]}, 3)
    exchange("a slain defender does not answer", {"attack": 60}, {"life": 1}, 5)
    exchange("counter uses its own stat", {"attack": 1},
             {"attack": 1, "counter_attack": 50}, 9)
    exchange("shots are unanswered", {"ranged_attack": 8}, {}, 11, kind=K.RANGED)
    exchange("evasion", {"flags": ["Ловкость"]}, {}, 13)

    fx["morale_share"] = {"melee": camod.morale_kill_share(K.MELEE),
                          "counter": camod.morale_kill_share(K.COUNTER),
                          "ranged": camod.morale_kill_share(K.RANGED)}
    fx["riders"] = [
        {"ability": "Смертельное касание", "kind": 1,
         "expected": camod.rider_fires("Смертельное касание", K.COUNTER)},
        {"ability": "Смертельное касание", "kind": 0,
         "expected": camod.rider_fires("Смертельное касание", K.MELEE)},
        {"ability": "Парализующее касание", "kind": 1,
         "expected": camod.rider_fires("Парализующее касание", K.COUNTER)},
    ]
    return fx


def status_fixture() -> dict:
    """Duration arithmetic, stacking policies and tick ordering."""
    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "stacking": {p.name: i for i, p in enumerate(stmod.Stacking)},
          "durations": [], "sequences": []}

    for base, conc, dmod, resist, rdur, thaum in (
            (6, 3, 100, 7, 100, 2), (6, 3, 200, 0, 0, 0), (6, 3, 50, 0, 0, 0),
            (4, 0, 0, 20, 100, 0), (5, 2, 100, 4, 50, 1), (3, 0, 0, 0, 0, 0)):
        fx["durations"].append({
            "base": base, "concentration": conc, "duration_mod": dmod,
            "target_resist": resist, "resist_duration": rdur,
            "thaumaturgy": thaum,
            "expected": stmod.effective_duration(base, conc, dmod, resist,
                                                 rdur, thaum)})

    def seq(label, unit_kw, effects, rounds, reduce_by=0, reduce_tags=()):
        u = Combatant(name="u")
        for k, v in unit_kw.items():
            setattr(u, k, v)
        u.life_base = unit_kw.get("life", 30)
        u.stamina_base = 10
        u.morale_base = 10
        specs = []
        for e in effects:
            spec = dict(e)
            specs.append(spec)
            stmod.apply(u, stmod.StatusEffect(
                id=e["id"], name=e.get("name", ""), duration=e.get("duration", -1),
                power=e.get("power", 0), tick=e.get("tick", {}),
                stacking=stmod.Stacking[e.get("stacking", "REFRESH")],
                prevents_action=e.get("prevents_action", False),
                hostile=e.get("hostile", False),
                tags=tuple(e.get("tags", [])),
                decay_per=tuple(e["decay_per"]) if e.get("decay_per") else None))
        if reduce_by:
            stmod.reduce_duration(u, reduce_by, tags=tuple(reduce_tags))
        for _ in range(rounds):
            stmod.tick_round(u)
        can, why = stmod.can_act(u)
        fx["sequences"].append({
            "label": label, "unit": unit_kw, "effects": specs, "rounds": rounds,
            "reduce_by": reduce_by, "reduce_tags": list(reduce_tags),
            "after": {"life": u.life, "stamina": u.stamina, "morale": u.morale,
                      "alive": u.alive, "statuses": len(u.statuses),
                      "can_act": can, "blocked_by": why,
                      "durations": sorted(e.duration for e in u.statuses)},
        })

    surge = {"id": "dark_surge", "name": "Всплеск Тьмы", "duration": 3,
             "tick": {"life": -4, "stamina": -2, "morale": -2},
             "stacking": "CUMULATIVE", "hostile": True, "tags": ["curse"]}

    seq("one round still ticks", {"life": 30}, [dict(surge, duration=1)], 1)
    seq("three rounds tick three times", {"life": 30}, [surge], 4)
    seq("cumulative stacks", {"life": 40}, [surge, surge, surge], 1)
    seq("maximum keeps the strongest", {"life": 30}, [
        {"id": "squire", "power": 2, "stacking": "MAXIMUM"},
        {"id": "squire", "power": 5, "stacking": "MAXIMUM"},
        {"id": "squire", "power": 3, "stacking": "MAXIMUM"}], 0)
    seq("refresh extends", {"life": 30}, [
        {"id": "bless", "duration": 2, "stacking": "REFRESH"},
        {"id": "bless", "duration": 5, "stacking": "REFRESH"}], 0)
    seq("unique ignores the second", {"life": 30}, [
        {"id": "mark", "duration": 2, "stacking": "UNIQUE"},
        {"id": "mark", "duration": 9, "stacking": "UNIQUE"}], 0)
    seq("shortening hits only hostiles", {"life": 30}, [
        dict(surge, duration=5),
        {"id": "bless", "name": "Благословение", "duration": 5}], 0, reduce_by=2)
    seq("tagged shortening", {"life": 30}, [
        {"id": "poison", "duration": 4, "hostile": True, "tags": ["poison"]},
        {"id": "curse", "duration": 4, "hostile": True, "tags": ["curse"]}],
        0, reduce_by=2, reduce_tags=["poison", "bleeding"])
    seq("web decays against a weak target", {"life": 30, "attack": 5,
        "counter_attack": 3}, [{"id": "web", "name": "Паутина", "duration": 6,
        "prevents_action": True, "hostile": True,
        "decay_per": ["attack_group", 10]}], 1)
    seq("web decays faster against a strong one", {"life": 30, "attack": 25,
        "counter_attack": 8}, [{"id": "web", "name": "Паутина", "duration": 6,
        "prevents_action": True, "hostile": True,
        "decay_per": ["attack_group", 10]}], 1)
    seq("a tick can kill", {"life": 3}, [surge], 1)
    seq("permanent never ages", {"life": 30}, [{"id": "innate", "duration": -1}], 20)
    return fx


def roster_fixture() -> dict:
    """A SELF-CONTAINED pack: bindings and tables embedded, not read.

    Every other fixture describes inputs the test constructs. This one has to
    carry the .var-derived TABLES too, because the real ones live in
    packs/<id>/data/ which is gitignored and machine-local. A test that read
    them would pass or fail depending on whose machine ran it — worthless in CI.

    The records below are shaped like the real ones (compound rows included) but
    are ours, so nothing here redistributes anyone's content.
    """
    units = [
        {"index": 1, "label": "", "Name": "Мечник", "Life": 17, "Attack": 7,
         "CounterAttack": 7, "Defence": 3, "RangedDefence": 5, "Resist": 1,
         "Speed": 2, "Stamina": 10, "Morale": 10, "Subtype": [1, 6],
         "Abilityes": [{"ref_label": "Parry", "ref": 10},
                       {"ref_label": "Bundle", "ref": 11}]},
        {"index": 2, "label": "", "Name": "Ополченец", "Life": 12, "Attack": 5,
         "CounterAttack": 4, "Defence": 2, "Speed": 2, "Stamina": 10,
         "Morale": 10, "Abilityes": []},
        {"index": 3, "label": "", "Name": "Лучник", "Life": 10, "Attack": 3,
         "RangedAttack": 6, "ShootingRange": 5, "Ammo": 6, "Speed": 2,
         "Stamina": 10, "Morale": 10,
         "Abilityes": [{"ref_label": "Dangling", "ref": 99},
                       {"ref_label": "Empty", "ref": 0}]},
    ]
    upgrades = [
        # a plain scalar row
        {"index": 10, "label": "", "Name": "Парирование", "Only Once": 1,
         "Need": [0], "Upg Type": 4, "Quantity": 2},
        # THE CASE THAT MATTERS: a compound row, parallel lists.
        {"index": 11, "label": "", "Name": "Младшая нежить", "Only Once": 1,
         "Need": [0], "Upg Type": [1, 60, 30], "Quantity": [1, 1, 1]},
    ]
    abilities = [
        {"index": 1, "label": "", "Name": "Жизнь", "Number": 1, "Numeric": 1},
        {"index": 2, "label": "", "Name": "Защита", "Number": 4, "Numeric": 1},
        {"index": 3, "label": "", "Name": "Иммунитет к яду", "Number": 60},
        {"index": 4, "label": "", "Name": "Бронебойный удар", "Number": 30},
    ]
    bindings = {
        "1": {"name": "Жизнь", "hook": "STAT_PASSIVE", "handler": "stat_delta",
              "params": {"stat": "life"}, "uses": 3},
        "4": {"name": "Защита", "hook": "STAT_PASSIVE", "handler": "stat_delta",
              "params": {"stat": "defence"}, "uses": 2},
        "60": {"name": "Иммунитет к яду", "hook": "STATUS_RESIST",
               "handler": "immunity", "params": {"against": "яд"}, "uses": 1},
        # deliberately unbound — a unit carrying it must still build
        "30": {"name": "Бронебойный удар", "hook": "DEFENCE_APPLY",
               "handler": "", "uses": 4},
    }

    import tempfile, os as _os, json as _json
    with tempfile.TemporaryDirectory() as tmp:
        d = _os.path.join(tmp, "fixture_pack")
        _os.makedirs(_os.path.join(d, "data"))
        with open(_os.path.join(d, "bindings.json"), "w", encoding="utf-8") as fh:
            _json.dump({"pack": "fixture_pack", "abilities": bindings}, fh,
                       ensure_ascii=False)
        for name, records in (("unit", units), ("unit_upg", upgrades),
                              ("ability_num", abilities)):
            with open(_os.path.join(d, "data", "%s.json" % name), "w",
                      encoding="utf-8") as fh:
                _json.dump({"file": "%s.var" % name, "records": records}, fh,
                           ensure_ascii=False)

        reg = content_mod.AbilityRegistry()
        handlermod.register_all(reg)
        db = content_mod.ContentDb.load(
            "fixture_pack", d, reg,
            {"unit": "unit.json", "unit_upg": "unit_upg.json",
             "ability_num": "ability_num.json"})
        r = rostermod.Roster(db)

        # Keyed by CANONICAL ID. Display names are localization and cannot key
        # a fixture: NH uses 11 names for more than one record. The name is kept
        # as a field so the fixture stays readable.
        built = {}
        for cid in r.ids():
            b = r.build(cid)
            if b is None or b.unit.name == "Пусто":
                continue
            built[cid] = {
                "name": b.unit.name,
                "content_id": b.content_id,
                "provenance": b.provenance,
                "stats": {k: getattr(b.unit, k) for k in
                          ("life", "life_base", "attack", "counter_attack",
                           "defence", "ranged_defence", "resist", "speed",
                           "ranged_attack", "shooting_range", "ammo",
                           "stamina", "stamina_base", "morale", "morale_base")},
                "subtypes": sorted(b.unit.subtypes),
                "modifiers": [{"ability": m.ability, "handler": m.handler,
                               "hook": int(m.hook), "power": m.power,
                               "params": m.params, "source": m.source}
                              for m in b.unit.modifiers],
                "resolved": [[o, n] for o, n in b.resolved],
                "unresolved": [{"upgrade_index": u.upgrade_index,
                                "upgrade_name": u.upgrade_name,
                                "opcode": u.opcode if u.opcode is not None else -1,
                                "ability_name": u.ability_name,
                                "reason": u.reason} for u in b.unresolved],
                "complete": b.complete,
            }
        cov = r.coverage()
        return {
            "note": "generated by oracle/make_fixtures.py — do not hand-edit",
            "pack": "fixture_pack", "bindings": bindings,
            "tables": {"unit": units, "unit_upg": upgrades,
                       "ability_num": abilities},
            "ids": r.ids(), "names": r.names(), "built": built,
            "coverage": {"units": cov["units"], "complete": cov["complete"],
                         "partial": cov["partial"],
                         "blockers": [[list(k), v] for k, v in cov["blockers"]]},
        }


def legacy_rng_fixture() -> dict:
    """Genesis CRT compatibility vectors — docs/LEGACY_RNG.md.

    Published golden vectors first, so the fixture fails loudly if the port
    drifts from the recovered specification rather than merely from the oracle.
    Then longer sequences the doc does not publish, which catch divergence the
    short vectors would miss (32-bit wraparound over many steps, and the
    digit-extension path exercised repeatedly rather than once).
    """
    from legacy_rng import LegacyRng as L

    fx = {
        "note": "generated by oracle/make_fixtures.py — do not hand-edit",
        "source": "docs/LEGACY_RNG.md (EXP-R4A-001, EXP-R4B-001)",
        "raw": [], "bounded": [], "weighted": [], "epochs": [], "sequences": [],
    }
    # published raw vectors
    for seed in (1, 111, 0):
        r = L(seed)
        fx["raw"].append({"seed": seed,
                          "expected": [r.next_u15() for _ in range(8)]})
    # published bounded vectors, with call counts
    for bound in (0, 1, 10, 30000, 30001, 300000, 3000001):
        r = L(1)
        value = r.below(bound)
        fx["bounded"].append({"seed": 1, "bound": bound,
                              "expected": value, "advances": r.calls})
    # published weighted vector, including by-VALUE removal
    r = L(0)
    selected, after = r.weighted([7, 9, 7], [1, 1, 3], remove_selected=True)
    fx["weighted"].append({"seed": 0, "values": [7, 9, 7], "weights": [1, 1, 3],
                           "remove_selected": True,
                           "expected": selected, "weights_after": after,
                           "advances": r.calls})
    # recovered reseed epochs
    r = L()
    fx["epochs"].append({"kind": "map_generation", "map_seed": 0,
                         "effective": r.seed_map_generation(0), "state": r.state})
    r = L()
    fx["epochs"].append({"kind": "map_generation", "map_seed": 20260726,
                         "effective": r.seed_map_generation(20260726),
                         "state": r.state})
    for turn in (0, 1, 3, 97):
        r = L()
        r.seed_strategic_turn(111, turn)
        fx["epochs"].append({"kind": "strategic_turn", "map_seed": 111,
                             "turn": turn, "state": r.state})
    # unpublished longer runs: wraparound and repeated digit extension
    for seed, bound, n in ((1, 6, 32), (20260726, 100, 24), (7, 30001, 12),
                           (0, 3000001, 8)):
        r = L(seed)
        fx["sequences"].append({
            "seed": seed, "bound": bound,
            "expected": [r.below(bound) for _ in range(n)],
            "advances": r.calls,
        })
    return fx


def aura_fixture() -> dict:
    """Aura vectors for the GDScript port.

    `core/rules/auras.gd` is a 213-line port with no differential coverage, and
    `tests/scenarios/aura_and_poison.json` is referenced by nothing — the exact
    tested-but-inert shape the project's own discipline warns about. Auras are
    the highest-risk place for it, because they are DERIVED on every call from
    positions, sides, subtypes, liveness and stacking; a port that diverges on
    any one of those produces a plausible battle rather than an error.

    Each case declares a battlefield, units with positions, and auras projected
    by named sources, then records what the oracle computes: which aura ids are
    active per unit, the summed per-round tick, and the unit state after the tick
    is applied.
    """
    import auras as auramod

    SCOPE = {auramod.Scope.ADJACENT: "adjacent",
             auramod.Scope.BATTLEFIELD: "battlefield",
             auramod.Scope.SELF: "self"}
    SIDE = {auramod.Side.ALLY: "ally", auramod.Side.ENEMY: "enemy",
            auramod.Side.ALL: "all"}
    STACK = {auramod.Stacking.CUMULATIVE: "cumulative",
             auramod.Stacking.MAXIMUM: "maximum"}

    cases = []

    def case(label, unit_specs, aura_specs, width=7, height=7):
        """unit_specs: (name, side, q, r, subtypes, alive, life, stamina)
        aura_specs:  (source, id, scope, affects, stacking, power, tick,
                      only_subtypes, except_subtypes)"""
        field = bfmod.Battlefield(width, height)
        units, sides = {}, {}
        for (name, side, q, r, subs, alive, life, stam) in unit_specs:
            u = combat.Combatant(name=name, life=life, life_base=10,
                                 stamina=stam, stamina_base=10,
                                 morale=10, morale_base=10)
            u.alive = alive
            for sub in subs:
                u.subtypes.add(sub)
            units[name] = u
            sides[name] = side
            field.place(u, bfmod.Hex(q, r))

        by_source = {}
        for (src, aid, scope, affects, stacking, power, tick, only, exc) in aura_specs:
            a = auramod.Aura(id=aid, name=aid, scope=scope, affects=affects,
                             stacking=stacking, power=power, tick=dict(tick),
                             only_subtypes=tuple(only), except_subtypes=tuple(exc),
                             source=units[src])
            by_source.setdefault(units[src], []).append(a)

        def side_of(u):
            return sides[u.name]

        expected = []
        for name in sorted(units):
            u = units[name]
            active = sorted(a.id for a in
                            auramod.active_for(u, by_source, field, side_of))
            totals, _ = auramod.tick_for(u, by_source, field, side_of)
            auramod.apply_tick(u, totals)
            expected.append({
                "unit": name,
                "active": active,
                "tick": {k: v for k, v in sorted(totals.items())},
                "after": {"life": u.life, "stamina": u.stamina,
                          "morale": u.morale, "alive": u.alive},
            })

        cases.append({
            "label": label, "width": width, "height": height,
            "units": [{"name": n, "side": s, "q": q, "r": r,
                       "subtypes": sorted(subs), "alive": alive,
                       "life": life, "life_base": 10,
                       "stamina": stam, "stamina_base": 10,
                       "morale": 10, "morale_base": 10}
                      for (n, s, q, r, subs, alive, life, stam) in unit_specs],
            "auras": [{"source": src, "id": aid, "scope": SCOPE[scope],
                       "affects": SIDE[affects], "stacking": STACK[stacking],
                       "power": power, "tick": dict(tick),
                       "only_subtypes": list(only),
                       "except_subtypes": list(exc)}
                      for (src, aid, scope, affects, stacking, power, tick,
                           only, exc) in aura_specs],
            "expected": expected,
        })

    A, B, S, M, C = (auramod.Scope.ADJACENT, auramod.Scope.BATTLEFIELD,
                     auramod.Scope.SELF, auramod.Stacking.MAXIMUM,
                     auramod.Stacking.CUMULATIVE)
    ALLY, ENEMY, ALL = auramod.Side.ALLY, auramod.Side.ENEMY, auramod.Side.ALL

    # 1. adjacency, and the projector is not in its own adjacency
    case("adjacent reaches neighbours only", [
        ("leader", "a", 3, 3, [], True, 10, 10),
        ("near",   "a", 4, 3, [], True, 10, 10),
        ("far",    "a", 6, 3, [], True, 10, 10),
    ], [("leader", "valour", A, ALLY, M, 2, {}, [], [])])

    # 2. battlefield scope ignores distance
    case("battlefield scope reaches everyone", [
        ("leader", "a", 3, 3, [], True, 10, 10),
        ("far",    "a", 6, 3, [], True, 10, 10),
    ], [("leader", "banner", B, ALLY, M, 1, {}, [], [])])

    # 3. side filtering, including Side.ALL
    case("side filtering", [
        ("leader", "a", 3, 3, [], True, 10, 10),
        ("friend", "a", 4, 3, [], True, 10, 10),
        ("foe",    "b", 2, 3, [], True, 10, 10),
    ], [("leader", "ally_only", A, ALLY, M, 1, {}, [], []),
        ("leader", "foe_only",  A, ENEMY, M, 1, {}, [], []),
        ("leader", "everyone",  A, ALL, M, 1, {}, [], [])])

    # 4. MAXIMUM keeps only the strongest of the same id
    case("maximum stacking keeps the strongest", [
        ("l1",     "a", 3, 3, [], True, 10, 10),
        ("l2",     "a", 3, 4, [], True, 10, 10),
        ("target", "a", 4, 3, [], True, 10, 10),
    ], [("l1", "valour", A, ALLY, M, 2, {}, [], []),
        ("l2", "valour", A, ALLY, M, 5, {}, [], [])])

    # 5. CUMULATIVE keeps both
    case("cumulative stacking keeps both", [
        ("l1",     "a", 3, 3, [], True, 10, 10),
        ("l2",     "a", 3, 4, [], True, 10, 10),
        ("target", "a", 4, 3, [], True, 10, 10),
    ], [("l1", "presence", A, ALLY, C, 2, {}, [], []),
        ("l2", "presence", A, ALLY, C, 5, {}, [], [])])

    # 6. a dead source projects nothing
    case("a dead source projects nothing", [
        ("leader", "a", 3, 3, [], False, 10, 10),
        ("near",   "a", 4, 3, [], True, 10, 10),
    ], [("leader", "valour", A, ALLY, M, 2, {}, [], [])])

    # 7. subtype filters
    case("only_subtypes and except_subtypes", [
        ("leader", "a", 3, 3, [], True, 10, 10),
        ("undead", "a", 4, 3, ["нежить"], True, 10, 10),
        ("living", "a", 3, 4, [], True, 10, 10),
        ("beast",  "a", 2, 3, ["животное"], True, 10, 10),
    ], [("leader", "undead_only", A, ALLY, M, 1, {}, ["нежить"], []),
        ("leader", "not_beasts",  A, ALLY, M, 1, {}, [], ["животное"])])

    # 8. opposing ticks SUM rather than one winning, and caps apply
    case("life and decay ticks sum, then cap", [
        ("healer",  "a", 3, 3, [], True, 10, 10),
        ("wither",  "a", 3, 4, [], True, 10, 10),
        ("wounded", "a", 4, 3, [], True, 4, 3),
        ("full",    "a", 2, 3, [], True, 10, 10),
    ], [("healer", "life",  A, ALLY, M, 0, {"life": 3}, [], []),
        ("wither", "decay", A, ALLY, M, 0, {"stamina": -2}, [], [])])

    # 9. a tick can kill, and stamina floors at zero
    case("a tick can kill; stamina floors at zero", [
        ("reaper", "a", 3, 3, [], True, 10, 10),
        ("dying",  "b", 4, 3, [], True, 2, 1),
    ], [("reaper", "death", A, ENEMY, M, 0, {"life": -5, "stamina": -4}, [], [])])

    return {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
            "cases": cases}


def rng_fixture() -> dict:
    fx = {
        "note": "generated by oracle/make_fixtures.py — do not hand-edit",
        "seed": 42,
        "algorithm": "fnv1a-lcg-2^31",
        "streams": {},
        "fnv1a": {},
    }
    for stream, sides in (("attack", 100), ("chip", 6), ("combat", 20), ("level_up", 37)):
        r = Rng(fx["seed"])
        fx["streams"]["%s:%d" % (stream, sides)] = [r.roll(sides, stream) for _ in range(16)]
    for name in ("attack", "chip", "combat", "level_up", ""):
        fx["fnv1a"][name] = Rng.fnv1a(name)
    return fx


def write(path: str, payload: dict) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    print("wrote %s" % path)


if __name__ == "__main__":
    dest = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(dest, exist_ok=True)
    write(os.path.join(dest, "rng_fixture.json"), rng_fixture())
    write(os.path.join(dest, "legacy_rng_fixture.json"), legacy_rng_fixture())
    write(os.path.join(dest, "pipeline_fixture.json"), out)
    write(os.path.join(dest, "action_fixture.json"), action_fixture())
    write(os.path.join(dest, "turn_fixture.json"), turn_fixture())
    write(os.path.join(dest, "content_fixture.json"), content_fixture())
    write(os.path.join(dest, "battlefield_fixture.json"), battlefield_fixture())
    write(os.path.join(dest, "scenario_fixture.json"), scenario_fixture())
    write(os.path.join(dest, "scenario_content_fixture.json"), scenario_content_fixture())
    write(os.path.join(dest, "modifier_fixture.json"), modifier_fixture())
    write(os.path.join(dest, "counter_fixture.json"), counter_fixture())
    write(os.path.join(dest, "status_fixture.json"), status_fixture())
    write(os.path.join(dest, "roster_fixture.json"), roster_fixture())
    write(os.path.join(dest, "aura_fixture.json"), aura_fixture())
