"""Generate the cross-language fixtures the GDScript tests consume.

    python3 oracle/make_fixtures.py tests/fixtures/

Writes rng_fixture.json and pipeline_fixture.json.

COMMIT THE OUTPUT. Do not wire this into the test run. A fixture regenerated at
test time records whatever the code currently does, so the test can never fail
and reviews show no diff — the same class of defect as the RNG bug, where every
check passed while the property under test was broken. Regeneration must be a
deliberate act whose diff is reviewable: if a formula changes, the changed
expected values are exactly what a reviewer needs to see.

The RNG-free pipeline cases carry exact expected values and are meaningful
before the RNG port is confirmed. The RNG-dependent cases assume test_rng.gd
passes, so run that first.
"""
import json
import os
import sys

import combat
import actions
import turn
from combat import AttackKind, Combatant, Rng

KIND = {"melee": AttackKind.MELEE, "counter": AttackKind.COUNTER, "ranged": AttackKind.RANGED}
KIND_ORD = {"melee": 0, "counter": 1, "ranged": 2}


def make(**kw):
    c = Combatant()
    for k, v in kw.items():
        if k == "flags":
            c.flags = set(v)
        else:
            setattr(c, k, v)
    return c


CASES = [
    ("healthy melee",            dict(name="a", attack=8, life_base=17, life=17), "melee"),
    ("additive bonus only",      dict(name="a", attack=8, attack_bonus=3, life_base=17, life=17), "melee"),
    ("wounded",                  dict(name="a", attack=8, life_base=17, life=5), "melee"),
    ("wounded + painless",       dict(name="a", attack=8, life_base=17, life=5,
                                      flags=["Не чувствует боли"]), "melee"),
    ("low stamina",              dict(name="a", attack=10, stamina=3, life_base=20, life=20), "melee"),
    ("zero stamina",             dict(name="a", attack=10, stamina=0, life_base=20, life=20), "melee"),
    ("zero stamina + tireless",  dict(name="a", attack=10, stamina=0, life_base=20, life=20,
                                      flags=["Неутомимый"]), "melee"),
    ("all three multipliers",    dict(name="a", attack=12, attack_bonus=2, stamina=2,
                                      life_base=30, life=6, morale=10, morale_base=10), "melee"),
    ("rage suppresses wound",    dict(name="a", attack=12, life_base=30, life=6,
                                      flags=["Боевое безумие"]), "melee"),
    ("counter attack stat",      dict(name="a", counter_attack=6, life_base=17, life=17), "counter"),
    ("ranged attack stat",       dict(name="a", ranged_attack=7, life_base=17, life=17), "ranged"),
]

DEF_CASES = [
    ("plain defence",        dict(name="d", defence=5, ranged_defence=7), "melee"),
    ("plain ranged defence", dict(name="d", defence=5, ranged_defence=7), "ranged"),
    ("defence bonus",        dict(name="d", defence=5, defence_bonus=3), "melee"),
    ("exhausted halving",    dict(name="d", defence=7, ranged_defence=9, stamina=0), "melee"),
    ("exhausted ranged",     dict(name="d", defence=7, ranged_defence=9, stamina=0), "ranged"),
    ("exhausted odd floor",  dict(name="d", defence=1, stamina=0), "melee"),
    ("exhausted tireless",   dict(name="d", defence=7, stamina=0, flags=["Неутомимый"]), "melee"),
]

out = {
    "note": "generated by oracle/make_fixtures.py — do not hand-edit",
    "attack_value": [],
    "defence_value": [],
    "multipliers": {"wound": [], "stamina": []},
    "roll_attack": [],
    "resolve": [],
}

for label, kw, kind in CASES:
    c = make(**kw)
    v, _ = combat.current_attack(c, KIND[kind])
    out["attack_value"].append({
        "label": label, "kind": KIND_ORD[kind], "unit": kw, "expected": round(v, 6),
    })

for label, kw, kind in DEF_CASES:
    c = make(**kw)
    v, _ = combat.current_defence(c, KIND[kind])
    out["defence_value"].append({
        "label": label, "kind": KIND_ORD[kind], "unit": kw, "expected": v,
    })

for pct in (100, 60, 50, 49, 40, 30, 20, 10, 1):
    c = make(life_base=100, life=pct)
    out["multipliers"]["wound"].append({"life": pct, "life_base": 100,
                                        "expected": round(combat.wound_mod(c)[0], 6)})
for st in (10, 6, 5, 4, 3, 2, 1, 0):
    c = make(stamina=st)
    out["multipliers"]["stamina"].append({"stamina": st,
                                          "expected": round(combat.stamina_mod(c)[0], 6)})

# RNG-dependent: exact sequences given a fixed seed
for attack in (1, 3, 5, 8, 13, 37):
    r = Rng(1234)
    out["roll_attack"].append({
        "attack": attack, "seed": 1234,
        "expected": [combat.roll_attack(attack, r)[0] for _ in range(12)],
    })

r = Rng(99)
seq = []
atk = make(name="Мечник", attack=8, attack_bonus=2, life_base=17, life=5, stamina=3)
dfn = make(name="Ополченец", defence=3, life_base=12, life=12)
for _ in range(10):
    d, _tr = combat.resolve_attack(atk, dfn, AttackKind.MELEE, r)
    seq.append(d)
out["resolve"].append({
    "label": "wounded exhausted swordsman vs militia", "seed": 99,
    "attacker": dict(name="Мечник", attack=8, attack_bonus=2, life_base=17, life=5, stamina=3),
    "defender": dict(name="Ополченец", defence=3, life_base=12, life=12),
    "kind": 0, "expected": seq,
})

def action_fixture() -> dict:
    """The catalogue plus decidable legality/cost cases.

    The catalogue is exported so the GDScript side builds Actions from data
    rather than duplicating a hardcoded list — which exists are content and
    differ per pack.
    """
    fx = {
        "note": "generated by oracle/make_fixtures.py — do not hand-edit",
        "catalogue": [],
        "cases": [],
    }
    for a in actions.CATALOGUE.values():
        fx["catalogue"].append({
            "id": a.id, "name": a.name, "target": list(actions.Target).index(a.target),
            "cost_stamina": a.cost.stamina, "cost_ammo": a.cost.ammo,
            "consumes_action": a.cost.consumes_action,
            "attack_surcharge": a.cost.attack_surcharge,
            "free_action_for": list(a.cost.free_action_for),
            "magnitude": a.magnitude, "is_attack": a.is_attack,
            "damage_scale": a.damage_scale,
            "suppresses": list(a.suppresses),
            "scales": [list(p) for p in a.scales],
            "excluded_targets": list(a.excluded_targets),
            "suppresses_counterattack": a.suppresses_counterattack,
            "notes": a.notes,
        })

    def case(label, action_id, **actor_kw):
        u = Combatant()
        u.stamina, u.stamina_base, u.ammo = 10, 10, 4
        for k, v in actor_kw.items():
            if k in ("flags", "subtypes"):
                setattr(u, k, set(v))
            else:
                setattr(u, k, v)
        a = actions.CATALOGUE[action_id]
        before = (u.stamina, u.ammo, u.action_spent)
        avail = a.availability(u)
        if avail is actions.Refusal.OK:
            a.pay(u)
        fx["cases"].append({
            "label": label, "action": action_id,
            "actor": {k: (sorted(v) if isinstance(v, set) else v)
                      for k, v in actor_kw.items()},
            "availability": list(actions.Refusal).index(avail),
            "resolved_stamina": a.cost.resolve(u).stamina if False else
                                a.cost.stamina + (1 if a.cost.attack_surcharge else 0),
            "after": {"stamina": u.stamina, "ammo": u.ammo, "action_spent": u.action_spent},
            "before": {"stamina": before[0], "ammo": before[1], "action_spent": before[2]},
        })

    case("frenzy, plenty of stamina", "frenzy")
    case("frenzy, exactly enough", "frenzy", stamina=3)
    case("frenzy, one short", "frenzy", stamina=2)
    case("healing with ammo", "healing")
    case("healing without ammo", "healing", ammo=0)
    case("turtle after acting", "turtle", action_spent=True)
    case("turtle at zero stamina", "turtle", stamina=0)
    case("frenzy while tireless at zero", "frenzy", stamina=0, flags=["Неутомимый"])
    case("carrion eater, ordinary unit", "carrion_eater")
    case("carrion eater, ratman after acting", "carrion_eater",
         subtypes=["Крысолюд"], action_spent=True)
    case("forced march overspend floors at zero", "forced_march", stamina=2)
    case("shield bash surcharge", "shield_bash")
    return fx


def turn_fixture() -> dict:
    """Action-point cases, emphasising the re-entry semantics."""
    fx = {"note": "generated by oracle/make_fixtures.py — do not hand-edit",
          "speed": [], "sequences": [], "initiative": []}

    for speed, stamina, flags in ((3, 10, []), (3, 4, []), (3, 3, []), (3, 2, []),
                                  (3, 0, []), (1, 0, []), (3, 0, ["Неутомимый"])):
        u = Combatant(speed=speed, stamina=stamina, stamina_base=10)
        u.flags = set(flags)
        fx["speed"].append({"speed": speed, "stamina": stamina, "flags": flags,
                            "expected": turn.effective_speed(u)[0]})

    def seq(label, steps, **kw):
        kw.setdefault("speed", 4)
        kw.setdefault("stamina", 10)
        kw.setdefault("stamina_base", 10)
        u = Combatant(name="u")
        flags = kw.pop("flags", [])
        for k, v in kw.items():
            setattr(u, k, v)
        u.flags = set(flags)
        turn.begin_round(u)
        for op, arg in steps:
            if op == "move":
                turn.spend_move(u, arg)
            elif op == "attack":
                turn.spend_attack(u)
            elif op == "rest":
                turn.rest(u)
            elif op == "new_round":
                turn.begin_round(u)
        fx["sequences"].append({
            "label": label, "setup": dict(kw, flags=flags), "steps": steps,
            "after": {"stamina": u.stamina, "movement_remaining": u.movement_remaining,
                      "steps_this_round": u.steps_this_round,
                      "action_spent": u.action_spent, "forced_rest": u.forced_rest,
                      "resting": u.resting},
        })

    seq("attack in place", [("attack", 0)])
    seq("move then attack", [("move", 1), ("attack", 0)])
    seq("out and back, then attack", [("move", 2), ("move", 2), ("attack", 0)])
    seq("split movement across a yield", [("move", 1), ("move", 1)])
    seq("act then keep moving", [("move", 1), ("attack", 0), ("move", 1)])
    seq("rest with recovery", [("rest", 0)], stamina=4, stamina_recovery=2)
    seq("rest caps at base", [("rest", 0)], stamina=9, stamina_recovery=5)
    seq("Зуд suppresses recovery", [("rest", 0)], stamina=4, stamina_recovery=3,
        flags=["Зуд"])
    seq("exhaustion forces next round", [("move", 1), ("attack", 0), ("new_round", 0)],
        stamina=2, stamina_recovery=1)
    seq("tireless pays nothing", [("move", 2), ("attack", 0)], stamina=1,
        flags=["Неутомимый"])

    for a_init, b_init, a_attacker, want in ((3, 5, True, 1), (5, 3, True, 0),
                                             (3, 3, True, 0), (3, 3, False, 1)):
        fx["initiative"].append({"a": a_init, "b": b_init, "a_attacker": a_attacker,
                                 "expected": want})
    return fx


def rng_fixture() -> dict:
    fx = {
        "note": "generated by oracle/make_fixtures.py — do not hand-edit",
        "seed": 42,
        "algorithm": "fnv1a-lcg-2^31",
        "streams": {},
        "fnv1a": {},
    }
    for stream, sides in (("attack", 100), ("chip", 6), ("combat", 20), ("level_up", 37)):
        r = Rng(fx["seed"])
        fx["streams"]["%s:%d" % (stream, sides)] = [r.roll(sides, stream) for _ in range(16)]
    for name in ("attack", "chip", "combat", "level_up", ""):
        fx["fnv1a"][name] = Rng.fnv1a(name)
    return fx


def write(path: str, payload: dict) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    print("wrote %s" % path)


if __name__ == "__main__":
    dest = sys.argv[1] if len(sys.argv) > 1 else "."
    os.makedirs(dest, exist_ok=True)
    write(os.path.join(dest, "rng_fixture.json"), rng_fixture())
    write(os.path.join(dest, "pipeline_fixture.json"), out)
    write(os.path.join(dest, "action_fixture.json"), action_fixture())
    write(os.path.join(dest, "turn_fixture.json"), turn_fixture())
