class_name Rng
extends RefCounted

## Deterministic integer RNG with named streams.
##
## PORTABILITY IS THE POINT. Stream seeding uses FNV-1a over the UTF-8 bytes of
## the stream name, never the host language's hash(). This file and
## oracle/combat.py must produce bit-identical sequences; tests/test_rng.gd
## asserts that against fixtures generated by the oracle.
##
##     FNV-1a 32-bit:  h = 2166136261;  for each byte: h ^= b; h *= 16777619
##     stream seed  :  fnv1a(name) XOR (seed * 2654435761), forced odd-nonzero
##     step         :  s = (1103515245 * s + 12345) mod 2^31
##
## The step function is a PLACEHOLDER. The original game's generator is
## unidentified (OPEN_QUESTIONS item 4). The roll surface is deliberately this
## narrow so replacing it is a one-file change.

const FNV_OFFSET: int = 2166136261
const FNV_PRIME: int = 16777619
const MASK32: int = 0xFFFFFFFF
const MASK31: int = 0x7FFFFFFF

var _seed: int
var _streams: Dictionary = {}
var calls: Dictionary = {}

func _init(p_seed: int) -> void:
	_seed = p_seed & MASK32

static func fnv1a(text: String) -> int:
	var h: int = FNV_OFFSET
	for b in text.to_utf8_buffer():
		h = ((h ^ b) * FNV_PRIME) & MASK32
	return h

func _state(stream: StringName) -> int:
	if not _streams.has(stream):
		var mixed: int = (_seed * 2654435761) & MASK32
		var s: int = (fnv1a(String(stream)) ^ mixed) & MASK31
		_streams[stream] = s if s != 0 else 1
		calls[stream] = 0
	return _streams[stream]

## Uniform integer in [0, x-1]. Returns 0 for x <= 1.
func roll(x: int, stream: StringName = &"combat") -> int:
	if x <= 1:
		return 0
	var s: int = _state(stream)
	s = (1103515245 * s + 12345) & MASK31
	_streams[stream] = s
	calls[stream] = int(calls[stream]) + 1
	return s % x
