extends SceneTree

## Cross-language determinism check.
##
## Run: godot --headless --script tests/test_rng.gd
##
## The fixture is generated by the Python oracle. If this fails, the two
## implementations have diverged and every replay, fixture and differential
## test downstream is meaningless — so this test runs first in CI.

const FIXTURE := "res://tests/fixtures/rng_fixture.json"

var failures: int = 0

func _check(ok: bool, what: String, detail: String = "") -> void:
	print("  %s  %s%s" % ["PASS" if ok else "FAIL", what,
		("  — " + detail) if detail != "" else ""])
	if not ok:
		failures += 1

func _init() -> void:
	var f := FileAccess.open(FIXTURE, FileAccess.READ)
	if f == null:
		push_error("fixture not found: %s" % FIXTURE)
		quit(1)
		return
	var fx: Dictionary = JSON.parse_string(f.get_as_text())
	f.close()

	print("RNG cross-language determinism (fixture seed %d, %s)"
		% [int(fx["seed"]), fx["algorithm"]])

	# 1. FNV-1a must match byte for byte.
	for name in (fx["fnv1a"] as Dictionary):
		var expected: int = int(fx["fnv1a"][name])
		var got: int = Rng.fnv1a(name)
		_check(got == expected, "fnv1a(%s)" % [JSON.stringify(name)],
			"got %d, expected %d" % [got, expected])

	# 2. Each stream must reproduce the oracle's sequence exactly.
	for key in (fx["streams"] as Dictionary):
		var parts: PackedStringArray = String(key).split(":")
		var stream: StringName = StringName(parts[0])
		var sides: int = int(parts[1])
		var expected: Array = fx["streams"][key]
		var rng := Rng.new(int(fx["seed"]))
		var got: Array = []
		for i in expected.size():
			got.append(rng.roll(sides, stream))
		var ok := true
		for i in expected.size():
			if int(expected[i]) != int(got[i]):
				ok = false
				break
		_check(ok, "stream %s" % key, "got %s" % [str(got.slice(0, 6))])

	# 3. Streams must not interfere.
	var a := Rng.new(7)
	var b := Rng.new(7)
	for i in 5:
		a.roll(10, &"attack")
	var a_chip: Array = []
	var b_chip: Array = []
	for i in 4:
		a_chip.append(a.roll(10, &"chip"))
		b_chip.append(b.roll(10, &"chip"))
	_check(str(a_chip) == str(b_chip),
		"streams independent — burning one does not shift another")

	print("\n%s" % ("ALL PASS" if failures == 0 else "%d FAILURES" % failures))
	quit(1 if failures > 0 else 0)
